### ISSUE TITLE
Release 0.12.0

### ISSUE THREAD

**Issue by MSeal** [nteract/papermill#102]
I could really use some of the recent changes in my current tasks. Any objections or particular PRs people want in this release? Was going to maybe wait for #100.

**Comment by betatim** [comment]
👍 to releasing after #100 is merged.

**Comment by betatim** [comment]
You want to setup travis so it deploys straight to PyPi on creating a new tag for the fully automagic release procedure? I'm a fan :)

**Comment by MSeal** [comment]
I like that idea too, but I can't put that together for this pass as I'm a little time strapped on some other commitments.

**Comment by MSeal** [comment]
Tagged and released

**Comment by betatim** [comment]
🚀
