### ISSUE TITLE
metadata info not set up in the cell 

### ISSUE THREAD

**Issue by evril7490** [nteract/papermill#106]
I was going through the example "Displaying Plots and Images Saved by Other Notebooks". However when I tried to display plots in another notebook, it failed. 
I found that, in the ceil that has the plot, the ceill has the keys:[u'output_type', u'data', u'metadata'], and the data field actuallly has the plot, but the metadata is a empty dictionary. It seems to me the metadata is not correctly set up for the ceil, but I am not sure what happened.
My ipython version is 5.3.0, python is 2.7. matplotlib version is 1.5.1.
![c1](https://user-images.githubusercontent.com/3451083/35123698-5a420854-fc71-11e7-9044-368c4ae16c59.JPG)

![c2](https://user-images.githubusercontent.com/3451083/35123700-5cd3a2a8-fc71-11e7-9f08-7c04a0fed8f4.JPG)

**Comment by MSeal** [comment]
Closing as this is now part of scrapbook project and likely has been fixed in the many cleanups in that transition.
