### ISSUE TITLE
Recognizing and setting parameter cells

### ISSUE THREAD

**Issue by rgbkrk** [nteract/papermill#109]
Hey all!

I'd love to make a menu option in nteract to denote a parameter cell in a single click within the nteract web app. As for design, for the moment just to make this simple with our current setup, I'd just be adding it to our menu:

<img width="173" alt="screen shot 2018-01-25 at 8 22 05 am" src="https://user-images.githubusercontent.com/836375/35399337-dd354870-01a8-11e8-9415-c1470228c7ff.png">

When it _is_ a parameterized cell, we can show a special border on the top or otherwise to indicate that it's a parameter cell. Haven't thought much on the design much here other than that we want some way to see it visually as users.

It's easy enough for me to mark it with a tag under the covers, _however_, it would be really nice to just set it in the cell's metadata (or even using the `metadata.name` attribute):

```json
{
  "cells": [
    {
      "cell_type": "code",
      "metadata": {
        "papermill": {
          "parameter_cell": true
        }
      },
      "outputs": [],
      "source": [
        "x = 3\n",
        "y=3"
      ]
    },
  ],
  "metadata": {},
  "nbformat": 4,
  "nbformat_minor": 2
}
```

What do you all think? Would `papermill` be open to looking for this metadata in addition to the current tagging mechanism?

**Comment by betatim** [comment]
Why the preference for setting a new key instead of adding a tag? Is it much easier to implement?

Should we also add a `default_parameter_cell` key to mirror the other tag in use?

I am not sure what I think. On the one hand it looks simple enough to add, on the other hand having two ways of doing things is prime territory for bugs :-/

**Comment by mpacer** [comment]
I’m with Tim on this one. But couldn’t the UI in nteract set that tag value? 

This way it’s still easy for anyone using any front end with tag access to use papermill.

**Comment by rgbkrk** [comment]
That settles it for me, I'll stick with setting the tag. Thanks!

**Comment by rgbkrk** [comment]
> This way it’s still easy for anyone using any front end with tag access to use papermill.

This is probably the most important note here which is that even if papermill supported both, if the metadata was setting it people wouldn't be able to see which are parameter cells in the classic notebook environment.
