### ISSUE TITLE
Notebook validation failed

### ISSUE THREAD

**Issue by ajasja** [nteract/papermill#115]
I get a notebook validation failed 

```
Notebook validation failed: {u'TEST_All': 7.2} is not valid under any of the given schemas:
{
 "TEST_All": 7.2
}
```

The code is the most basic possible:
```python 
import papermill as pm
pm.record("TEST_All",7.2)
```

![image](https://user-images.githubusercontent.com/19926/35667690-ee356cc8-072e-11e8-8d10-e246b15f1f92.png)

Using:
papermill: 0.12.1
Jupyter-notebook: 5.3.1
Python 2.7.11 |Anaconda 2.2.0 (32-bit)| (default, Mar  4 2016, 15:18:41) 

Any help is appreciated
Attached notebook: [TEST.zip](https://github.com/nteract/papermill/files/1684654/TEST.zip)
.

**Comment by ajasja** [comment]
Also, this is the output written to the stdout:
https://pastebin.com/hWa6hMNx

**Comment by MSeal** [comment]
Hmm I can't reproduce the issue with the version you have listed (or with slight variants) off fresh virtualenvs. Can you dump your `pip freeze` listing? IPython recently made some changes and you may need to update that dependency.

**Comment by ajasja** [comment]
Here is my [pip_freeze](https://pastebin.com/k7q4MtDU) output. Will try to reproduce in a fresh environment.

**Comment by ajasja** [comment]
Indeed I can't reproduce this in a [fresh](https://pastebin.com/yejtPjCp) env either. Sorry for the noise will try a fresh env before reporting next time:)

**Comment by ajasja** [comment]
Upgrading to:
```
    ipykernel:                          4.2.2-py27_0         --> 4.8.0-py27_0
    ipython:                            5.3.0-py27_0         --> 5.4.1-py27_2
    ipywidgets:                         5.2.2-py27_0         --> 7.1.1-py27_0
    nbformat:                           4.0.1-py27_0         --> 4.4.0-py27h8fb4f08_0
    widgetsnbextension:                 1.2.6-py27_0         --> 3.1.0-py27_0
```

Solved the issue.

**Comment by ajasja** [comment]
(I had to explicitly update ipython)

**Comment by MSeal** [comment]
Good to hear. IPython made some breaking changes recently with 5.3 to 5.4
