### ISSUE TITLE
TraitError: The 'timeout' trait of an ExecutePreprocessor instance must be an integer

### ISSUE THREAD

**Issue by ajasja** [nteract/papermill#116]
When trying to execute a notebook I get the following error:
```
TraitError: The 'timeout' trait of an ExecutePreprocessor instance must be an integer, but a value of None <type 'NoneType'> was specified.
```
Code:
```python
pm.execute_notebook(
   'TEST.ipynb',
   'TEST-out.ipynb',
   parameters = dict(test_param='3333')
)
```
Notebook: [TEST.zip](https://github.com/nteract/papermill/files/1684744/TEST.zip)
[Full stacktrace](https://pastebin.com/YHPyg5RG) 

Using:
papermill: 0.12.1
Jupyter-notebook: 5.3.1
Python 2.7.11 |Anaconda 2.2.0 (32-bit)| (default, Mar 4 2016, 15:18:41)

**Comment by MSeal** [comment]
I am not able to reproduce this issue with versions listed. Can you print your pip freeze and try it out with a fresh virtualenv?

**Comment by ajasja** [comment]
Here is my [pip_freeze](https://pastebin.com/k7q4MtDU) output. Will try to reproduce in a fresh environment.

**Comment by ajasja** [comment]
Explicitly upgrading Ipython and ipykernel solved the issue.
```
    ipykernel:                          4.2.2-py27_0         --> 4.8.0-py27_0
    ipython:                            5.3.0-py27_0         --> 5.4.1-py27_2
    ipywidgets:                         5.2.2-py27_0         --> 7.1.1-py27_0
    nbformat:                           4.0.1-py27_0         --> 4.4.0-py27h8fb4f08_0
    widgetsnbextension:                 1.2.6-py27_0         --> 3.1.0-py27_0
```
