### ISSUE TITLE
python2 install?

### ISSUE THREAD

**Issue by ironv** [nteract/papermill#122]
Can papermill be installed in a docker container with python2.7?  My docker container does not have a connection to the internet.  I have successfully installed the dependencies (botocore, boto3, tqdm, click, s3transfer).  When I try to install using `pip install --user papermill-0.12.3-py3-none-any.whl`  I get hte message `papermill-0.12.3-py3-none-any.whl is not a supported wheel on this platform`.  Any ideas?

**Comment by rgbkrk** [comment]
Yeah I think we'd need to ship a universal wheel (which I thought for sure we were). The filename you mentioned is for python3. How did you download it originally?

**Comment by ironv** [comment]
From `https://pypi.python.org/pypi/papermill`  (scroll to the end).   Any chance of getting the universal wheel soon?  Thank you!

**Comment by MSeal** [comment]
Hmm yes that is odd. If you do a simpler `pip install --user papermill==0.12.3` if will successfully install, but it appears to use the tar.gz file instead. I won't have time for a couple days at least to get at looking at the wheel generation.

**Comment by MSeal** [comment]
@ironv I fixed the release process to make universal wheels. Version 0.12.4 wheel installs on 2 and 3 (tested on my machine).
