### ISSUE TITLE
Feature Request: Dryrun

### ISSUE THREAD

**Issue by MSeal** [nteract/papermill#126]
It would be handy if we had a dryrun mode which parameterized a notebook and saved it to the output path without actually executing the cells. This would enable preparing notebooks for execution elsewhere or with alternative kernels in an upstream process. Should be relatively simple to add.

**Comment by betatim** [comment]
nitpick: might not call the command-line option `--dry-run` as I'd expect that to change absolutely nothing on disk, not even write a new notebook. Maybe `--prepare` or some such?

**Comment by rgbkrk** [comment]
`--apply-parameters`?

**Comment by MSeal** [comment]
`--prepare` or `--apply-parameters` both sounds reasonable... perhaps `--parameterize`, `--params-only`, or `--no-execute` as some other possibilities
