### ISSUE TITLE
nbconvert not working after running execute_notebook in papermill

### ISSUE THREAD

**Issue by Vednus** [nteract/papermill#129]
I'm using papermill to parameterize some notebooks which I'm then exporting as html reports using nbconvert. But, I've run into issues with nbconvert erroring out if I use it after running `pm.execute_notebook()`. Specifically, this line is the cause since it hijacks nbconvert's `Preprocessor.preprocess` method: https://github.com/nteract/papermill/blob/master/papermill/execute.py#L141

I ended up getting it to work by saving the original nbconvert preprocess method and then reassigning it after I've used papermill. But, I was wondering, is there a better way?

**Comment by MSeal** [comment]
Hmm yes I think we should instead be extending the `ExecutePreprocessor` class instead of monkey patching the parent class method. I'm not sure if there's subtle implications/assumptions in the repo which made that original change, but there's no comments saying so. We can give it a try and see if things are working.

**Comment by MSeal** [comment]
Hit this issue as well when trying to generate HTML of a papermill notebook node. Will try to get to a fix when I get a chance but any other developers who have a spare cycle this one is pretty irritating when hit.

**Comment by mpacer** [comment]
I just brought this up elsewhere but we can probably make a lot of this nicer by using jupyter machinery(since that’s what nbconvert is using under the hood). I’m not going to be able to put any cycles on this for the next couple weeks but if there is interest, afterward I can take a look at this.

**Comment by MSeal** [comment]
We'll snap a new version here in a week or so when some of the other open PRs merge, but fix is in master now.
