### ISSUE TITLE
papermill could warn me I forgot to provide a file extension for the output

### ISSUE THREAD

**Issue by thomasballinger** [nteract/papermill#157]
Maybe `.ipynb` and `.json` are the only reasonable choices here? Maybe just a warning?

**Comment by harsham4026** [comment]
@MSeal PR #207 addresses this issue. Can you please take a look into it?

**Comment by MSeal** [comment]
Awesome and thanks! Found the test issue blocking python 2 as well :)

**Comment by harsham4026** [comment]
@MSeal you can close this issue as well :)
