### ISSUE TITLE
Wrong encoding for reading notebooks on Windows

### ISSUE THREAD

**Issue by mjos** [nteract/papermill#160]
Hi,

we are unable to execute notebooks on Windows platform because the notebooks cannot be read due to incorrect file encoding. Notebooks are plain json files and as such encoded in UTF-8. However, the default encoding (on windows) is set according to the locale (in our case CP1250). Notebooks are read via `LocalHandler` in `iorw.py`. The function `io.open` is used, but no encoding specified and thus (incorrectly) set to CP1250. Would it be possible to fix this? There is the unfortunate problem of different approach in Python 2.7 and Python 3+ to handle file encoding. Thanks.

**Comment by MSeal** [comment]
Hi @mjos we should default to UTF-8. I'll look at getting this added quickly.

**Comment by mjos** [comment]
Thanks a lot!

**Comment by MSeal** [comment]
https://github.com/nteract/papermill/pull/162 fixes the issue -- I'll make a release this week with the changes.

**Comment by MSeal** [comment]
0.14.1 release includes fix
