### ISSUE TITLE
consider black for code formatting

### ISSUE THREAD

**Issue by alexandercbooth** [nteract/papermill#161]
[black](https://black.readthedocs.io/en/stable/index.html) is awesome! We use [prettier](https://prettier.io/) in the monorepo and it is 😍. If folks are interested, it could be a good small project for a new contributor at the sprints 😄

**Comment by betatim** [comment]
I'm quite happy with pep8 as style. So I'll be the grumpy old guy who suggests we don't change things unless there is a good reason.

🔥 Code churn for code churn's sake is for JS projects :p

**Comment by MSeal** [comment]
Going to give this a try, as we don't have any linter on the repo yet. We can configure it to be as much or as little PEP8 as we want to support. Today it requires us to be diligent and sometimes aggressive on external code submissions to conform.

**Comment by betatim** [comment]
> >    Code churn for code churn's sake is for JS projects :p

> Speaking like this will alienate others and their ability to work with you.

Sorry for that. The mindset of a day of friends who know each other very well trying to wind each other up in jest spilled over into the internet.

**Comment by MSeal** [comment]
Added black, but it's not in the instructions or commit hook paths. Editors can pick up the config and we can run `black .` whenever we want. Let's try this experiment for a while and if we really like it add it into our CI paths more explicitly.

**Comment by rgbkrk** [comment]
I'm certainly in favor, it especially helps when I'm away from Python for long periods of time. I'd prefer a formatter handle this for me so I can focus on the actual logic, docs, and API design.
