### ISSUE TITLE
Update papermill docs

### ISSUE THREAD

**Issue by MSeal** [nteract/papermill#169]
This is mostly a self-reminder as prep for Jupyter Con. We've made a lot of improvements to papermill this year -- some of them aren't transcribed to the docs well yet.

**Comment by willingc** [comment]
I've set up a webhook for RTD to autobuild on pushes in GitHub. Send me your RTD account name and I'll add you to the maintainer list too.

**Comment by willingc** [comment]
Any particular features or sections? If so, we can open a few doc issues for new contributors.

**Comment by MSeal** [comment]
Thanks for setting that up! The updated API docs and developer_guide help a lot here with docs now.

I think a better parameters section that described options for passing to the notebook would be beneficial. I get a lot of questions about that.

And a how-to-tag section for different notebook interfaces would help users.

I'll add these two as separate new contributor issues.
