### ISSUE TITLE
Improve reading notebooks from url that need accept json header

### ISSUE THREAD

**Issue by kafonek** [nteract/papermill#174]
Our notebooks are being stored in an [nbgallery](https://github.com/nbgallery/nbgallery) instance.  A generic `requests.get(notebook_url)` returns html.  Papermill's `execute.execute_notebook(notebook_url)` / `iowr.HttpHandler.read` do not offer a way to set a `{'Accept' : 'application/json'}` header in the request.

When we make a request on our own using accept json headers, we can write that notebook to file (`tempfile` or otherwise) and use Papermill as is.  It would be convenient to also be able to pass in a file-like object (`io.StringIO(resp.text)`), json (`resp.text`), and/or dictionary (`resp.json()`) of the downloaded notebook file rather than needing to write to file.

Thanks.

**Comment by MSeal** [comment]
Agreed -- and thanks for posting the issue. At a minimum the default for fetching should use that header. If you want to make the contribution @kafonek we'll gladly merge it (or get to making the change when we're settled back form JupyterCon).

I also need to make it easy to pass the JSON strings directly -- this likely means a slightly rework of the local file default handler in the iorw section.
