### ISSUE TITLE
Better record capabilities

### ISSUE THREAD

**Issue by MSeal** [nteract/papermill#175]
Challenges with record today:
- Doesn't _quite_ fit with the rest of papermill linear execution codebase (it was awkward to describe it as an additional feature of papermill this week, really felt like describing a second less developed library)
- Requires translation to JSON for everything (dataframes are painful here)
- Reading records into a result dataframe isn't always the shape you'd expect
- Not as modular as other components of papermill where we can register custom operators (hard to do cross notebook?)

I was thinking perhaps we should promote notebook data recording to a new repository in nteract (@betatim suggested some names -- `scrapbook.glue(stuff)`)

A few ideas regardless of where it lives, on the topic:
- Use arrow for dataframe like saves?
- Still accept JSON (backwards compatibility)
- Some other binary forms (plug and play options?)
- Support other standard storage forms as plug and play options (pandas does this -- i.e. steal pandas conversion options as plugins as they're nice features)
- Maybe lean on some of the other data transport ideas between kernels and components from elsewhere nteract??
- Think a little more about secondar language support (R is nice but we'd want support in many languages for the most common transports)

Thoughts welcome!

**Comment by betatim** [comment]
I (obviously) think this is a good idea. Potentially even having a way to store "stuff" that other languages can't load. Current record functionality promises that R notebooks can load things recorded by Python notebooks. This is useful.

However it leaves me to make up conventions around storing extra bits of data related to a notebook. Providing some helpers/opinions around that would be nice. And the "scrapbook" metaphor hopefully conveys that this is meant for kind of loose odds and ends that in the olden days you might have glued to the back of your notebook or some such. "stuff that doesn't quite fit, but should be kept".

**Comment by MSeal** [comment]
FYI: https://github.com/nteract/scrapbook
