### ISSUE TITLE
Add `--engine` command-line argument

### ISSUE THREAD

**Issue by betatim** [nteract/papermill#177]
Right now notebooks can only be executed locally using nbconvert.

It would be nice to be able for the user to pick an "engine". For example to run notebooks on [kaggle via their API](https://github.com/Kaggle/kaggle-api) or on a BinderHub. It would also let you swap the current nbconvert engine for a xeus(?) based local runner.

First step would be to introduce the command-lien argument with it defaulting to "nbconvert". Preserving the current behaviour. Then add a binder or kaggle engine and exposing it.

**Comment by MSeal** [comment]
:+1:

**Comment by MSeal** [comment]
Implementation here would need to make an engine register class following translators / iorw files. Will be interesting to see what generic methods we'd want to support the first two engines.

**Comment by betatim** [comment]
Another (speculative) use of this would be an engine that inspects the notebooks metadata to find out what dependencies the notebook has and then creates an environment (docker, virtual env, conda env) to run the notebook in on demand.
