### ISSUE TITLE
Add --version to CLI

### ISSUE THREAD

**Issue by MSeal** [nteract/papermill#193]
We should push our version tags into --version for the CLI interface.

**Comment by harsham4026** [comment]
@MSeal could you please explain me the significance of this?

**Comment by MSeal** [comment]
Most CLI tools have a `--version` option to print the version of the tool. Papermill's command line doesn't have any way to tell what version of papermill it's using without checking the pip package. Something like http://click.pocoo.org/5/options/#callbacks-and-eager-options would do the trick.

**Comment by harsham4026** [comment]
@MSeal the PR #209 addresses this issue.
