### ISSUE TITLE
Is it possible to run with Jupyter Notebook (web env)?

### ISSUE THREAD

**Issue by cqcn1991** [nteract/papermill#20]
As I see in the doc, papermill requires 

> Parameterizing a Notebook.
> To parameterize your notebook designate a cell with the tag parameters. Papermill looks for the parameters cell and replaces those values with the parameters passed in at execution time.

However, I don't find places to add tag to cell in original Jupyter Notebook. Is it only available in nteract?

**Comment by Madhu94** [comment]
@cqcn1991 I think cell tagging was made available in Jupyter 5.0, what version are you using ?

**Comment by rgbkrk** [comment]
Amusingly, nteract desktop doesn't support tags yet. Jupyter does though and this is the UI for accessing it:

<img width="482" alt="screen shot 2017-08-09 at 10 23 56 am" src="https://user-images.githubusercontent.com/836375/29134992-7a3e5756-7ced-11e7-998a-77ccab0cb45f.png">

<img width="1176" alt="screen shot 2017-08-09 at 10 28 06 am" src="https://user-images.githubusercontent.com/836375/29134991-7a3d1c1a-7ced-11e7-87f4-135f584f7d3f.png">

We'll want to bring it into nteract once we have a UI plan for tags in nteract.

**Comment by rgbkrk** [comment]
Thanks for asking the question, it's clear we'll want another guide that shows you the workflow. Closing for now.

**Comment by cqcn1991** [comment]
@Madhu94 @rgbkrk  Thanks for you all. I just upgraded to 5.0, and really have no idea on the new tag feature. Now I can try for papermill now.
