### ISSUE TITLE
Further separate IO and notebook execution so the python API can operate on nbformat objects

### ISSUE THREAD

**Issue by VincentBLortie** [nteract/papermill#200]
The current python API allows the user to execute a notebook by providing paths to input and output files, and potentially a path to a parameters file, through the `execute_notebook` function of `execute.py`.

Unfortunately, there doesn't seem to be a way to call papermill directly with nbformat notebook objects.

I'd like your thoughts on this suggestion:

- The calls to `load_notebook_node` and `write_ipynb` could be moved out of `execute_notebook`
- Alternatively, everything between these two calls could be extracted into a new public method that takes in and returns nbformat objects
- In either of these cases, the following lines should probably be extracted from the top of `_parameterize_notebook` and run at the same time as the rest of the IO, so that `_parameterize_notebook` is guaranteed to receive a dictionary:

```python
    # Load from a file if 'parameters' is a string.
    if isinstance(parameters, six.string_types):
        parameters = read_yaml_file(parameters)
```

Another option, which keeps the calls to iorw in execute_notebook but opens doors for users:

- input may be either a path or an object. If it is a path, then an object is loaded using load_notebook_node
- output may be either a path or None. An output file is only written if the path is not None
- return the resulting nbformat object in all cases
- nothing changes for the parameters

**Comment by MSeal** [comment]
I think the logic would better fit with the #177 Issue around adding engine abstractions. The NBConvert engine could have an interface for taking it's internal object and parameterizing it.

Though in reality you're just applying parameterization to a notebook object. I'd rather not expose a lot of internal details of NBConvert in papermill, so maybe we can think about engines optonaoly exposing their representation layer, or being able to translate papermills's abstraction (in the case of NBConvert model today it would mostly return the same object type).

I do like the idea of allowing the iowr or execute layers to be a little more flexible to passing a model along rather than just a filename.

Do you have thoughts based on this line of thinking that you see fitting the desired goal?

Also I will be disconnected from the internet for several days, so likely won't respond until next week.

**Comment by VincentBLortie** [comment]
I am a bit out of my depth here, since I haven't explored much of the codebase of nbconvert and other related projects.

To clarify, when you say you'd rather not expose too many internal details of NBConvert, you're referring to the nbformat representation? It's what `execute_notebook` returns, and I assumed (perhaps incorrectly) that it was somewhat of a standard for representing Jupyter notebooks.

No worries about being disconnected, I don't have much time tonight to think about this anyway.

**Comment by VincentBLortie** [comment]
I can see the fit with #177, and I think my suggestion could be an intermediary stage in that direction: Would you want file paths at the engine's interface? Would the engine be calling iorw? My intuition is that reading and writing the notebooks, and parameterization, should not be the engine's responsibility. Something vaguely like this:

![engine_diagram](https://user-images.githubusercontent.com/1178934/45235421-d56ff680-b2a6-11e8-8148-4316609297a8.png)

Does this make any sense, is it too restrictive for #177, or am I completely off track?

**Comment by rgbkrk** [comment]
> To clarify, when you say you'd rather not expose too many internal details of NBConvert, you're referring to the nbformat representation?

IIRC, this would be the internal details of nbconvert would be things like the configurability layers, the preprocessors, etc.

Standardizing on the notebook data structure is a-ok, that's all self contained in the `nbformat` python library.

**Comment by MSeal** [comment]
@VincentBLortie That makes perfect sense, I think you got the model right. Mostly I wanted to emphasize we could formalize the layering around the Engine concept -- pretty much as you diagrammed.

@rgbkrk phrased the constraints better than I did, but I think you guessed what was intended based on the IN / OUT sections of your diagram.

I'll look to start on the engine PR this week for #177 to get this ball rolling if that helps.

**Comment by VincentBLortie** [comment]
If you have time to look at #177 this week, then great :) but if you had other things lined up, I might find some time to contribute an intermediary step as described in my issue either later this week or this weekend

**Comment by MSeal** [comment]
Started the engine PR so we have a base closer to the picture above to work from. I _think_ it has most of what we need.

I also gave you permissions to the linked PR repo in case you want to push changes directly to that PR, as I might not finish it for a couple days.

**Comment by MSeal** [comment]
I believe the new engine achieves this feature. Feel free to reopen if you think there's some additional needed.
