### ISSUE TITLE
Add Azure Blob Storage backend

### ISSUE THREAD

**Issue by xhochy** [nteract/papermill#205]
I would like to use `papermill` but store my notebooks on Azure Blob Storage. To achieve this, I think all it needs is implementing the same interface as done for S3 in `s3.py` and then registering it with `papermill_io.register("wasb://", WASBHandler)`?

**Comment by MSeal** [comment]
Hi xhochy!

Yes that's all you have to add. You can follow the pattern in https://github.com/nteract/papermill/pull/184 which added Azure Data Lake Storage. The same libraries it used may also be usable for Azure Blob Storage (haven't checked).

**Comment by MSeal** [comment]
Also https://github.com/nteract/papermill/blob/master/DEVELOPMENT_GUIDE.md#io-sources--sinks may be of use for how this works and what's expected with additions
