### ISSUE TITLE
What if the user passes --parameters and --parameters_raw multiple options just give a warning or error instead of updating?

### ISSUE THREAD

**Issue by harsham4026** [nteract/papermill#210]
If the user passes --parameters_raw, --parameters_file, --parameters_yaml etc all parameter options at the same time, can we throw the error or show some warning to use any one of them instead of updating the dictionary? @MSeal please let me know your thoughts about it.

**Comment by MSeal** [comment]
Actually we use multiple parameter inputs often. A bunch of different inputs all generate a separate parameter(s) argument and we combine them all at the end to generate a cohesive execution. So it's a feature of the system to let multiple inputs combine rather than fail.

**Comment by harsham4026** [comment]
ok. Got it!
