### ISSUE TITLE
HDFS File System support?

### ISSUE THREAD

**Issue by harsham4026** [nteract/papermill#211]
Hi @MSeal I was wondering if there is any plan or way that we can support HDFS as well along with the storage systems like s3 and ADL?. Please let me know your thoughts :)

**Comment by MSeal** [comment]
That seems reasonable to add and likely wouldn't be too difficult. If you want to take a shot at it we can get it included to the library.

**Comment by harsham4026** [comment]
yes @MSeal implementing the methods for enabling the HDFS as well. Will raise a PR soon with all the changes :).

**Comment by harsham4026** [comment]
#217 addresses this issue.

**Comment by moritzmeister** [comment]
I see #217 got closed with the recommendation of giving it another try with a new PR.

Is anyone working on it, or are there plans to pick it up later?

**Comment by MSeal** [comment]
Not that I am aware of. If you wanted to give it a go I'd be happy to review any PRs

**Comment by MSeal** [comment]
https://github.com/nteract/papermill/pull/470 solves this -- will go out with papermill 2.0 release in the next couple weeks.
