### ISSUE TITLE
Google Bucket File System Support

### ISSUE THREAD

**Issue by luke14free** [nteract/papermill#213]
Along with the other filesystem requests, it would be amazing to be able to use papermill with Google Buckets filesystems. I'll try to contribute to this myself as well.

**Comment by bnaul** [comment]
I'm interested in implementing this; the same thing for pandas was straightforward https://github.com/pandas-dev/pandas/pull/22704. Does it make sense to do so before #257? I'm personally not thrilled about installing all the Azure and S3 IO tools to use papermill and I can imagine other people feeling the same way about `gcsfs`.

**Comment by MSeal** [comment]
If you get a PR open for this feature I can get https://github.com/nteract/papermill/issues/257 implemented so we can start isolating dependencies and we can hold off merging until it's in place. The dependency isolation is needed for papermill 1.0 so I need to do it regardless.

**Comment by gogasca** [comment]
We are planning to launch a workaround to run Papermill in GCS. Please take a look at this: https://blog.kovalevskyi.com/how-to-submit-jupyter-notebook-for-overnight-training-on-gcp-4ce1b0cd4d0d  ideally we would like to have native support. Not sure what is the status so far. Interested in contributing too.
