### ISSUE TITLE
Why does the output of "execute_notebook" return a "nbformat" notebook instead of a `papermill.api.Notebook`?

### ISSUE THREAD

**Issue by choldgraf** [nteract/papermill#220]
I noticed that the output of `execute_notebook` returns a "regular" nbformat-style notebook, while `read_notebook` returns a nifty papermill notebook object. Is there a particular reason for this discrepancy? Could be nice to have papermill notebook objects as an output to `execute_notebook` in case people are executing them interactively

**Comment by MSeal** [comment]
https://github.com/nteract/papermill/pull/204 is working on unifying abstractions. We've had asks for nbformat-style notebooks as the internal store for papermill but that PR is where we should make the final decision about internal storage for version 1.0. I would welcome feedback / ideation there or in the associated issue https://github.com/nteract/papermill/issues/177. It might make sense to use the smarter object as our wrapping store.

**Comment by choldgraf** [comment]
sounds good - shall I close this issue in lieu of the others? (or feel free to do so yourself)

**Comment by MSeal** [comment]
To follow -up the decision that was made was to keep with nbformat and move the Notebook object into https://github.com/nteract/scrapbook as the place for the more informated notebook model.
