### ISSUE TITLE
Obscure error message if `jupyter` binary not present

### ISSUE THREAD

**Issue by larsrinn** [nteract/papermill#230]
Hey,

*update. I solved the issue myself. The issue was me installing `jupyter` locally ( `pip install jupyter -t .`) and not including the binary into the zipped file. However, I think I still have some suggestions for improvements of papermill*

I'm trying to setup a pipeline to run parametrized notebooks on AWS Lambda using papermill. While doing this, I wasted many hours until I realized, I didn't include the `jupyter` script (installed to `/usr/local/bin/jupyter` on my mac by default).

To facilitate development and packaging, I'm using [docker-lambda](https://github.com/lambci/docker-lambda/blob/master/python3.6/build/Dockerfile).

All the code along with a description on how to get it running (as far as I got), can be found here: https://github.com/larsrinn/papermill-lambda 
Also I made the zipped file uploaded to S3 and deployed to lambda from there publicly available: https://s3.eu-central-1.amazonaws.com/papermill-lambda/lambda.zip 

Here's the output of running the lambda function locally. Everything works great:
```
$ docker run -v "$PWD":/var/task papermill-lambda-test
START RequestId: 151e3734-ad1f-48ff-bf93-30151eb6336b Version: $LATEST
http://example.com
100%|██████████| 4/4 [00:01<00:00,  4.19it/s]
END RequestId: 151e3734-ad1f-48ff-bf93-30151eb6336b
REPORT RequestId: 151e3734-ad1f-48ff-bf93-30151eb6336b Duration: 5038 ms Billed Duration: 5100 ms Memory Size: 1536 MB Max Memory Used: 94 MB

true
$ 
```

However, running the code using test events on Lambda, I always receive the error `Kernel died before replying to kernel_info`:

```
START RequestId: 6d78022f-ce35-11e8-8dff-9b4971437921 Version: $LATEST
http://example.com
Kernel died before replying to kernel_info: RuntimeError
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 14, in lambda_handler
    url=url,
  File "/var/task/papermill/execute.py", line 70, in execute_notebook
    _execute_parameterized_notebook(nb, kernel_name, progress_bar, log_output, start_timeout)
  File "/var/task/papermill/execute.py", line 136, in _execute_parameterized_notebook
    processor.preprocess(nb, {})
  File "/var/task/papermill/preprocess.py", line 92, in preprocess
    cwd=path,
  File "/var/task/papermill/preprocess.py", line 114, in start_new_kernel
    kc.wait_for_ready(timeout=startup_timeout)
  File "/var/task/jupyter_client/blocking/client.py", line 120, in wait_for_ready
    raise RuntimeError('Kernel died before replying to kernel_info')
RuntimeError: Kernel died before replying to kernel_info

END RequestId: 6d78022f-ce35-11e8-8dff-9b4971437921
REPORT RequestId: 6d78022f-ce35-11e8-8dff-9b4971437921	Duration: 2163.71 ms	Billed Duration: 2200 ms 	Memory Size: 1024 MB	Max Memory Used: 141 MB	
```

I could fix this by copying the `jupyter` "binary" to the zipped file and modifying the path slightly. Now I can run parametrized notebooks on Lambda, great :)

But I think I would have figured out how to do that in seconds but not hours if the error message had been clearer. Maybe you can add a hint to the traceback that probably the binary is missing (I don't know whether this error can be cause by other issues, though).

When looking at the `jupyter` script, I was wondering whether it is called at all by `papermill`. Essentially it is just a wrapper around `jupyter_core.commands.main`. Wouldn't it be easier to call the commands directly? I didn't dive into the papermill code, though. So I can't assess whether it's as simple as I assume to not require that script.

**Comment by MSeal** [comment]
Do you have the notebook which was causing this issue? And was this running the latest papermill version, or an older version?

It's likely more related to the kernel running rather than papermill. The "Kernel died before replying to kernel_info" is the "oh no something went wrong" for papermill trying to launch a kernel and failing. Papermill doesn't directly call jupyter scripts but it uses nbconvert which has more complicated setup concerns. It might be an issue there we can help address. I'd want to reproduce it before I'd be sure of these guesses though.

**Comment by betatim** [comment]
Can you start a jupyter kernel in your old setup/zip file? What does running `jupyter-kernelspec list` inside the lambda environment print before you fix the problem?

I think papermill assumes you have the kernel that the notebook you want to run uses already installed and setup. As there are many different kernels you could use they aren't a dependency of papermill.

Maybe we can check from papermill's side if the kernel used by the notebook is installed/available and produce an error that says "Notebook wants to use 'python3' as kernel but it isn't installed". The simplest way to do this would be to run the equivalent of `jupyter-kernelspec list` which is part of the `jupyter_client` package that is already a dependency.

**Comment by larsrinn** [comment]
No, in the old zip file none of the `jupyter ...` commands worked because that script wasn't included. I was able to get everything working by copying them manually into the zip and hacking the `PATH` environment variable. Sorry if my edits above didn't make that clear. I don't really think this is a bug in papermill. Just if the error messages had been clearer, I wouldn't have spent that much time on figuring what's going on. But I guess I can't blame you or the maintainers of jupyter for my lack of knowledge how this works.

As the `jupyter` script that's required to be in the path only calls the `main()` method, I guessed it would be fairly easy to not require it and instead call the correct methods directly. But probably this would rather be addressed directly to jupyter?

**Comment by sambogoat** [comment]
Stumbled across this issue trying to debug the same error message running papermill on lambda. 

@larsrinn my approach is essentially same as that in your papermill-lambda repo. Could i ask how how you hacked the PATH and the zip to resolve the issue? Sounds like this may circumvent hours of debugging the issue and so any pointers would be gratefully received thx.

The version in papermill-lambda master still generates the 'Kernel died before replying to kernel_info' error so i assume your fix wasn't reflected back to the repo.

**Comment by larsrinn** [comment]
Phew, it's many moons ago I worked last on that problem. We never really went further with using papermill inside a lambda function. But I commited everything back to my repo. "Hacking the path" is done in https://github.com/larsrinn/papermill-lambda/blob/a20706f4ec1170aec0c3c8a7f4b7343a6256863d/lambda_function.py#L7

This required copying in the ipython binaries: https://github.com/larsrinn/papermill-lambda/blob/a20706f4ec1170aec0c3c8a7f4b7343a6256863d/Dockerfile-deploy#L9

Essentially it was this commit which got it working. I don't remember the details though.
https://github.com/larsrinn/papermill-lambda/commit/a20706f4ec1170aec0c3c8a7f4b7343a6256863d#diff-f1286dc3720f1fd5741584eaea47e3e3

But at least following the instructions in the readme should get you a working lambda function.

**Comment by sambogoat** [comment]
As a late follow-up on this, what got this working for me was to add PYTHONPATH to the list of environment variables in the lambda config. 

Without this the changes by @larsrinn didn't resolve the issue alone.

**Comment by mohdlee** [comment]
I had the same issue as @sambogoat but it's on python3.7 runtime. On python3.6, the environment variable is populated by the lambda by default. I've created at issue at https://github.com/awsdocs/aws-lambda-developer-guide/issues/135

It's also good to take a look at https://github.com/NUS-ALSET/lambda-nbconvert as a comparison when troubleshooting
