### ISSUE TITLE
Execute notebook from string

### ISSUE THREAD

**Issue by JosephP91** [nteract/papermill#243]
Hello everybody,

is it possibile to execute an ipython notebook from a string, instead reading it from a file? I am in the situation where I have a JSON notebook string and I need to pass it to papermill without writing it into a file. Is it possible?

**Comment by JosephP91** [comment]
Hello Matthew,

thank you for the response. Digging in the code I came up with the same exact solution. I think it would be awesome to expose a flexible mechanism like that. In this way a user can code its own custom handlers, as in my case, without duplicating code or hacking it but simply extending it.

Thank you,

Giuseppe Persico
Software Engineer
Il 13 nov 2018, 00:25 +0100, Matthew Seal <notifications@github.com>, ha scritto:

**Comment by Madhu94** [comment]
I'm picking this up!

**Comment by Madhu94** [comment]
@MSeal Would it be enough to tweak the ``LocalHandler.read`` to 

```
 def read(self, path):
        try:
            with chdir(self._cwd):
                with io.open(path, 'r', encoding="utf-8") as f:
                    return f.read()
        except IOError:
            # The papermill_io singleton reads this string via
            # nbformat, so validation would happen there.
            return path
``` 

This makes it work with both the api and cli usages of papermill, whereas using io.StringIO can be used only for the api.

**Comment by MSeal** [comment]
The concern with that exact approach is that you may have IOErrors unrelated to the argument being a string that would now be masked and hidden from the user. I'd make the except path do something like:

```
...
except IOError as e:
  try:
    json.loads(path)
    return path
  except:
    raise e
```

You might want to adjust that slightly to accomodate io.String and regular strings.

**Comment by Madhu94** [comment]
Good point, thanks!

**Comment by Madhu94** [comment]
Are we sure we want to support passing in ``io.StringIO`` object ? There are a lot of assumptions in the codebase about path being string-like (like ``get_pretty_path``, ``get_handler`` which checks if the string ``startswith`` scheme, et all)

**Comment by MSeal** [comment]
If it looks to be a pain, then I'd skip io.StringIO support.

**Comment by rgbkrk** [comment]
I talked a little bit with @mwouts about making use of this possible with the command line via: `papermill - s3://bucket/myoutputnotebook.ipynb` where [the `-` indicates stdin, as is common in *nix land](https://unix.stackexchange.com/a/16364)
