### ISSUE TITLE
Error on executing a notebook without parameter tag

### ISSUE THREAD

**Issue by betatim** [nteract/papermill#245]
I sometimes (more often than I want to admit) run `papermill a-nb-withot-parameter-cell.ipynb output.ipynb -p alpha 0.1` mostly because I edited the notebook in nteract and forget to press save or get the paths wrong.

Should it be an error/warning to execute a notebook that has no parameters and specify parameters on the command-line?

**Comment by MSeal** [comment]
Hmm a warning might be a good idea. I wouldn't want to error out as there's valid use cases for not tagging such any particular cell.

**Comment by Madhu94** [comment]
I'll take this.
