### ISSUE TITLE
Hiding Ingested Parameters when executing with `--report-mode`

### ISSUE THREAD

**Issue by LeonardAukea** [nteract/papermill#253]
I want to be able to hide the ingested parameters at least when running in report mode. Since a new cell is created by papermill when feeding in params, there is no way to add metadata for that cell in the notebook. When you want to execute a notebook in order to generate some sort of report where no code is visible I think that in most cases the ingested parameters should be hidden. #135 

I'm not super familiar with the codebase but would it be as simple as adding: 

```
newcell.metadata['jupyter']['source_hidden'] = True
``` 

Around here -> https://github.com/nteract/papermill/blob/master/papermill/execute.py#L112-L114 ?

----
Furthermore, it would be nice to have a neat way of handling secrets. According to my understanding it's currently not a very good idea to ingest secrets as parameters since, they are made available in the output notebook.

**Comment by betatim** [comment]
That looks like it is the right place. Do you want to make a PR to add that functionality? I think it makes sense to add this metadata also for generated cells.

Secrets are tricky. Right now I'd use environment variables to make them available to the notebook. This isn't a absolutely, will always work solution though, see https://github.com/nteract/papermill/pull/232 for some discussion on the topic of setting environment variables for things like remote execution engines :-/ Ideas would be welcome, probably best in a new issue.

**Comment by LeonardAukea** [comment]
Ok, I hope that small fix would do the trick #254
