### ISSUE TITLE
Cron, Conda, and Papermill

### ISSUE THREAD

**Issue by djchou** [nteract/papermill#255]
just curious what the best way is to have papermill run on a cron job using an anaconda environment.  

I've tried calling papermill from the conda environment but I get this strange message:
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/en/7.x/python3/ for mitigation steps.

Is there a best practice for how to use conda, cron and papermill?

**Comment by djchou** [comment]
I ended up writing a python script and calling the script using the conda interpreter.

**Comment by RobertAron** [comment]
I got here through a similar problem, but with docker. I was able to fix it by setting environment variables inside the docker container. For me that looked like this:

```docker
ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
```
