### ISSUE TITLE
Specifying YAML file as parameter input generates warning

### ISSUE THREAD

**Issue by nickynicolson** [nteract/papermill#264]
Docs specify that parameters may be specified in a YAML file:

    Options:
     (snip)
      -f, --parameters_file TEXT      Path to YAML file containing parameters.

Specification of a .yaml parameters file on the command line generates the following warning:

    The specified input file (example.yaml) does not end in '.ipynb' or '.json'

The execution proceeds and parameters are read, but the warning is misleading.

**Comment by MSeal** [comment]
Good catch. I'll get a fix in for that.
