### ISSUE TITLE
Documenting entry points.

### ISSUE THREAD

**Issue by janfreyberg** [nteract/papermill#266]
Since entry points are in the [latest release](https://github.com/nteract/papermill/commit/29ccb408d5865f950f019b5aa3f5a2640ca23aeb) it would be nice to document how to develop new entry points so third-party developers can do so.

I will take a stab at this, but I wanted to open an issue to discuss the format. At the moment, there are two main sections in the docs: *Installation* and *Usage*. My proposal would be to add a third section titled e.g. *Developing papermill* that has general development advice for the library overall, and specific sub-sections for developing an engine and an IO handler.

Thoughts?

**Comment by betatim** [comment]
Sounds like a good plan.

"Developing" is totally fine and should be our baseline. Pondering if by using a slightly different word we can increase the number of people who think changing/tweaking papermill is something they can and should do? Some random words that might be suitable: extending, developing, contributing, modifying, changing ... papermill.

**Comment by janfreyberg** [comment]
I like *extending* or *customising*, that's nice and accessable!

**Comment by MSeal** [comment]
Yes please! That'd be a great contribution.

**Comment by willingc** [comment]
Perhaps the outline should be similar to:
- Extending papermill
    - High level description and visual about engines and io
    - New engines
         - How to develop a new engine
         - How to install and use
         - A runnable example or template
     - New IO handler
         - How to develop
         - How to install and use
         - Example or template

**Comment by janfreyberg** [comment]
I like that! I will try and finally make a start on this today.

**Comment by willingc** [comment]
Thanks @janfreyberg. Just an FYI that I have an open PR #292 for a docs refactor. The docs for Extending papermill would be great after the `usage-cli` section. Please let me know if you need anything too.
