### ISSUE TITLE
Progress bar fails if `seaborn` is imported

### ISSUE THREAD

**Issue by bnaul** [nteract/papermill#270]
Related to #165:  on `papermill==0.16.2`, `seaborn==0.9.0`:
```
> python -c "import seaborn as sns; import papermill as pm; pm.execute_notebook(input_path='report_mode_test.ipynb', output_path='/tmp/out.ipynb')"

HBox(children=(IntProgress(value=0, max=3), HTML(value='')))
```

Looks like the notebook environment check is not right here? It looks like `tqdm.autonotebook` does handle this case properly so maybe it would make more sense to just use that instead.

```
python -c 'import seaborn as sns; from tqdm.autonotebook import tqdm; [i for i in tqdm(range(5))]'
100%|█████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 23250.02it/s]
```

**Comment by betatim** [comment]
Sounds like a good idea, especially if `tqdm` will do the tedious work of figuring out if we are in a notebook or not :)

Do you want to make a PR for this?
