### ISSUE TITLE
Detect notebook is run in papermill

### ISSUE THREAD

**Issue by JannesKlaas** [nteract/papermill#286]
Dear community,
I am looking to make some code in my notebooks dependent on the fact that the notebook is run through papermill. 
This would greatly simplify my workflow as I could use the same notebook I use in development straight in papermill. One solution would be to use papermill to set a parameter indicating the notebook is run in papermill. But maybe there is a more elegant method? Is there any difference in the runtime environment that I could detect? My search has not yielded any results so far.

Thanks a million, any help would be greatly appreciated,
Jannes

**Comment by VincentBLortie** [comment]
This is just an opinion, but using a parameter for this seems like the most elegant solution to me, whereas inferring the environment (dev vs prod) from the runtime environment seems like it may be a bit abstruse for future maintainers of your notebook and could break with later releases of papermill.

**Comment by JannesKlaas** [comment]
That is a good point, thanks!
