### ISSUE TITLE
AttributeError: 'PapermillExecutePreprocessor' object has no attribute 'setup_preprocessor'

### ISSUE THREAD

**Issue by JarnoRFB** [nteract/papermill#289]
Hi, I just tried to run papermill for the first time on an empty notebook, just inserting a single parameter like

    $ papermill papermill_try_out.ipynb out.ipynb -p alpha 0.6

While the notebook out is created and the parameter inserted the execution of the notebook stops with the error

    AttributeError: 'PapermillExecutePreprocessor' object has no attribute 'setup_preprocessor'

I tried on both Linux and Windows with JupyterLab.

**Comment by JarnoRFB** [comment]
Hey, I installed via pip. It somehow was a strange issue that made pip think it was version 5.4, even so 5.3 was still there. I had to manually remove it from the side package directory and reinstall, then it worked. Thanks for the hint! I guess we can close this?

**Comment by MSeal** [comment]
Yeah, sounds like an environment / pip one-off issue. Going to close, and good to hear it was easily resolved
