### ISSUE TITLE
On MacOs: ModuleNotFoundError: No module named 'azure.datalake' 

### ISSUE THREAD

**Issue by danielsc** [nteract/papermill#291]
I might have missed something very obvious here, but somehow, papermill does not seem to work for me on MacOs.

$ python -c 'import papermill'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/danielsc/.azureml/envs/gcloud/lib/python3.6/site-packages/papermill/__init__.py", line 8, in <module>
    from .api import display, record, read_notebook, read_notebooks
  File "/Users/danielsc/.azureml/envs/gcloud/lib/python3.6/site-packages/papermill/api.py", line 17, in <module>
    from .iorw import load_notebook_node, list_notebook_files
  File "/Users/danielsc/.azureml/envs/gcloud/lib/python3.6/site-packages/papermill/iorw.py", line 20, in <module>
    from .adl import ADL
  File "/Users/danielsc/.azureml/envs/gcloud/lib/python3.6/site-packages/papermill/adl.py", line 2, in <module>
    from azure.datalake.store import core, lib
ModuleNotFoundError: No module named 'azure.datalake'

$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.2
BuildVersion:	18C54

$ pip freeze
absl-py==0.6.1
adal==1.0.2
ansiwrap==0.8.3
applicationinsights==0.11.6
appnope==0.1.0
argcomplete==1.9.4
asn1crypto==0.24.0
astor==0.7.1
azure-cli-command-modules-nspkg==2.0.2
azure-cli-core==2.0.43
azure-cli-nspkg==3.0.3
azure-cli-profile==2.1.1
azure-common==1.1.14
azure-datalake-store==0.0.40
azure-graphrbac==0.40.0
azure-mgmt-authorization==0.50.0
azure-mgmt-containerregistry==2.1.0
azure-mgmt-keyvault==1.1.0
azure-mgmt-nspkg==2.0.0
azure-mgmt-resource==2.0.0
azure-mgmt-storage==2.0.0
azure-nspkg==2.0.0
azure-storage-blob==1.3.1
azure-storage-common==1.3.0
azure-storage-nspkg==3.0.0
backcall==0.1.0
backports.tempfile==1.0
backports.weakref==1.0.post1
bcrypt==3.1.4
bleach==3.1.0
boto3==1.9.83
botocore==1.12.83
certifi==2018.4.16
cffi==1.11.5
chardet==3.0.4
Click==7.0
cloudpickle==0.6.1
colorama==0.3.9
contextlib2==0.5.5
cryptography==2.3
cycler==0.10.0
dask==1.0.0
decorator==4.3.0
defusedxml==0.5.0
docker==3.5.0
docker-pycreds==0.3.0
docutils==0.14
entrypoints==0.3
Flask==1.0.2
future==0.17.1
gast==0.2.0
grpcio==1.17.0
h5py==2.8.0
humanfriendly==4.16.1
idna==2.7
ipython==7.2.0
ipython-genutils==0.2.0
isodate==0.6.0
itsdangerous==1.1.0
jedi==0.13.2
Jinja2==2.10
jmespath==0.9.3
joblib==0.13.1
jsonpickle==0.9.6
jsonschema==2.6.0
jupyter-client==5.2.4
jupyter-core==4.4.0
Keras==2.1.5
Keras-Applications==1.0.6
Keras-Preprocessing==1.0.5
kiwisolver==1.0.1
knack==0.4.1
Markdown==3.0.1
MarkupSafe==1.1.0
mistune==0.8.4
mkl-fft==1.0.10
mkl-random==1.0.2
msrest==0.5.4
msrestazure==0.5.0
nbconvert==5.4.0
nbformat==4.4.0
ndg-httpsclient==0.5.1
networkx==2.2
numpy==1.15.4
oauthlib==2.1.0
pandas==0.23.4
pandocfilters==1.4.2
papermill==0.17.1
paramiko==2.4.1
parso==0.3.1
pathspec==0.5.6
pexpect==4.6.0
pickleshare==0.7.5
Pillow==5.3.0
prompt-toolkit==2.0.7
protobuf==3.6.1
ptyprocess==0.6.0
pyasn1==0.4.4
pycparser==2.18
Pygments==2.2.0
PyJWT==1.6.4
PyNaCl==1.2.1
pyOpenSSL==18.0.0
pyparsing==2.3.0
python-dateutil==2.7.3
pytz==2018.5
PyWavelets==1.0.1
PyYAML==3.13
pyzmq==17.1.2
requests==2.21.0
requests-oauthlib==1.0.0
ruamel.yaml==0.15.51
s3transfer==0.1.13
scikit-image==0.14.1
scikit-learn==0.20.2
scipy==1.1.0
SecretStorage==2.3.1
six==1.11.0
tabulate==0.8.2
tensorboard==1.10.0
tensorboardX==1.4
tensorflow==1.10.0
termcolor==1.1.0
testpath==0.4.2
textwrap3==0.9.1
toolz==0.9.0
tornado==5.1.1
tqdm==4.29.1
traitlets==4.3.2
urllib3==1.24.1
wcwidth==0.1.7
webencodings==0.5.1
websocket-client==0.48.0
Werkzeug==0.14.1

**Comment by willingc** [comment]
Hi @danielsc.

It looks as if several of the dependencies that you have are a lower version than what installed on my system.

What I would try first is to upgrade the package install:

`pip install -U papermill`

If that doesn't update the dependencies to version similar to below:

`pip install -U papermill --force-reinstall`

Let us know how it goes. If those do not resolve it (they should :smile:), I can walk you through installing in a virtual environment. 

My output for comparison.
```
~/projects/nteract/testproject/tests 40s
mytestenv ❯ python -c 'import papermill'

~/projects/nteract/testproject/tests
mytestenv ❯ pip freeze
adal==1.2.0
ansiwrap==0.8.3
appnope==0.1.0
asn1crypto==0.24.0
azure-common==1.1.17
azure-datalake-store==0.0.40
azure-storage-blob==1.4.0
azure-storage-common==1.4.0
backcall==0.1.0
bleach==3.1.0
boto3==1.9.83
botocore==1.12.83
certifi==2018.11.29
cffi==1.11.5
chardet==3.0.4
Click==7.0
cryptography==2.5
decorator==4.3.0
defusedxml==0.5.0
docutils==0.14
entrypoints==0.3
future==0.17.1
idna==2.8
ipython==7.2.0
ipython-genutils==0.2.0
jedi==0.13.2
Jinja2==2.10
jmespath==0.9.3
jsonschema==2.6.0
jupyter-client==5.2.4
jupyter-core==4.4.0
MarkupSafe==1.1.0
mistune==0.8.4
nbconvert==5.4.0
nbformat==4.4.0
numpy==1.16.0
pandas==0.23.4
pandocfilters==1.4.2
papermill==0.17.1
parso==0.3.1
pexpect==4.6.0
pickleshare==0.7.5
prompt-toolkit==2.0.7
ptyprocess==0.6.0
pycparser==2.19
Pygments==2.3.1
PyJWT==1.7.1
python-dateutil==2.7.5
pytz==2018.9
PyYAML==3.13
pyzmq==17.1.2
requests==2.21.0
s3transfer==0.1.13
six==1.12.0
testpath==0.4.2
textwrap3==0.9.1
tornado==5.1.1
tqdm==4.29.1
traitlets==4.3.2
urllib3==1.24.1
wcwidth==0.1.7
webencodings==0.5.1
```

**Comment by danielsc** [comment]
Thanks a lot -- setting up a new conda environment with
```
conda create --name simple python --no-default-packages
```
solved it

**Comment by willingc** [comment]
Fantastic @danielsc!

**Comment by danielsc** [comment]
I now figured out what was really going on:
Apparently, I have been hitting this conda issue: https://github.com/conda/conda/issues/7173 where somehow isolation between environments is broken by shared access to ~/.local/lib/python3.6.
The conda creation above helped only because I forgot to set python=3.6 -- so I ran python 3.7, which of course wouldn't use ~/.local/lib/python3.6....
The resolution it to `rm -rf ~/.local/lib/python3.6`
