### ISSUE TITLE
Use name not tags for unique cell objects

### ISSUE THREAD

**Issue by mpacer** [nteract/papermill#30]
In 

https://github.com/nteract/papermill/blob/7b717e763528915dd77865d418011d86f54b528c/papermill/execute.py#L157-L163

it makes the assumption that only one cell will have any parameters being defined in the notebook and raises an error if this is not the case.

We have `name` as a cell-level metadata field in the [nbformat spec](http://nbformat.readthedocs.io/en/latest/format_description.html#cell-metadata) that specifically requires values to be unique across the notebook. If you want to maintain this uniqueness qualifier it would be cleaner to require setting the name on a cell rather than a tag.

If the only reason to not do this is that the UI for setting a `name` vs. `tags` is more inconvenient, that suggests we have a frontend UI issue. In that case… using tags is just a compromise made for the current state of front-ends and should probably be deprecated as soon as possible in favour of setting `name` properly.

**Comment by ewmassey** [comment]
I really like this and strongly prefer it to our current strategy. How do you set a name for a cell in Jupyter?

**Comment by rgbkrk** [comment]
OMG, there's a `name` metadata field? Holy crap, I probably would have abused that in nteract to put in UUIDs. 😲  Then I'd be able to support commenting and other niceties really easily.

**Comment by rgbkrk** [comment]
As @mpacer points out, there's no way to set this with the current Jupyter UI. We'd need to introduce something into the classic notebook (as well as nteract).

Adding it on to the contextual cell menu is one `<li>` and some state management away.

![screen shot 2017-09-06 at 9 56 04 am](https://user-images.githubusercontent.com/836375/30124328-aa6c3f4e-92e9-11e7-861c-9167df893744.png)

It's tempting!

**Comment by rgbkrk** [comment]
I'm really interested in setting the name field using our current unique IDs and allowing users to override them with their own names (like parameters in this case).

**Comment by rgbkrk** [comment]
For classic, we need to make an extension for this. Are there JS APIs for managing the uniqueness of cell names in jupyter/notebook @mpacer?

**Comment by mpacer** [comment]
I don't think there is anything for maintaining uniqueness.

Note to fully support this requires modifying all of the cell creation machinery. 

E.g., name metadata shouldn't be included in the duplicate of a cell once it's copied and pasted. 

Name shouldn't persist on both cells after a split, perhaps it should be removed on both.

Merge should probably remove the name altogether.

Can you think of anything else?

**Comment by mpacer** [comment]
Aside: @rgbkrk I'd love to see how you get these demo visualisations to work so quickly.

It might be nice to have a little tab off to the left part of the top of the cell bar that displays the name that can be double clicked to edit (like the name of the document).

**Comment by rgbkrk** [comment]
> I'd love to see how you get these demo visualisations to work so quickly.

Sometimes I'll cheat and just modify things on the DOM directly. In the case of this one, I hit `command-shift-f` in Atom (on nteract/nteract) to search across all files and typed in "Convert to Markdown" so that I could find where similar menu items were. I then copied the `<li>` React element from one of these other menu items and changed the text to match "Denote as Parameter Cell".

The reason I get it done quickly in nteract is mostly because of how our dev setup works and because I know the code base/tooling really well. I'd be happy to walk you through it!

**Comment by rgbkrk** [comment]
> It might be nice to have a little tab off to the left part of the top of the cell bar that displays the name that can be double clicked to edit (like the name of the document).

I can tell I'm not going to like that, let me give it a go though. 😄

**Comment by rgbkrk** [comment]
Referencing an old issue for something similar for top level metadata: https://github.com/nteract/nteract/issues/1503

**Comment by MSeal** [comment]
Going to close this issue as it's been more established that tags are the way to go for now on this topic.
