### ISSUE TITLE
Add path interpolation using parameters and special keys

### ISSUE THREAD

**Issue by MSeal** [nteract/papermill#300]
papermill highlight_dates.ipynb ./highlight_dates_run_cli_{start_date}_{stop_date}_{%guid}.ipynb -p start_date 2011-01-01 -p stop_date 2014-02-02

Use string / int parameters and a few built-in keywords to generating notebook paths,

**Comment by VincentBLortie** [comment]
I like that the example looks like python string formatting: most users will be familiar with the syntax. Perhaps there's another way than % to signify that a parameter is a built-in? (afaik, % isn't something you can use in a python format string). How about a prefix like "pm_" for values automatically provided by papermill?

Actually, from an implementation point of view, do you see any danger in using the user's input as a format string and calling .format directly?

**Comment by MSeal** [comment]
I think format syntax would be the clearest and easiest. We may want to raise an error if a format string isn't filled in would be the only thing to keep in mind.
