### ISSUE TITLE
Display warnings generated in executed notebook

### ISSUE THREAD

**Issue by clzarecki** [nteract/papermill#305]
If a warning is generated in an executed notebook, the main notebook never receives the warning, so it would potentially be hidden unless the executed notebook is opened manually.

**Comment by MSeal** [comment]
When you say main notebook vs executed notebook, do you mean when executing papermill from inside a notebook the messages from the underlying notebook are not captured? I believe if you set the --log-output option it will log those (and everything else). It would be challenging to distinguish warning messages in the underlying notebook and probably out of scope to capture those outputs specifically.

**Comment by clzarecki** [comment]
Thank you for your help, MSeal! It works just the way I wanted it to, displaying stderr when executing a notebook from another one. I will close this issue.
