### ISSUE TITLE
Notebook.parameters is empty dict

### ISSUE THREAD

**Issue by tlinhart** [nteract/papermill#308]
Hi,

I'm building a UI for scheduling notebook runs. My idea is to let users pick a notebook, specify when (and optionally how often) to run it, and also provide a form with parameters defined in the notebook that they would adjust. I thought I would just call `papermill.api.read_notebook` and grab parameters from `parameters` of returned `Notebook` object, but it returns an empty dictionary. From the code it seems it reads the parameters from `papermill` metadata attribute, which is present only after processing (in the output notebook).

Is this a feature? Or is there other way how to read parameters from the input notebook?

**EDIT:**
As my primary goal is to get the names of parameters from the notebook (to be able to build the form), I use this for notebooks with Python kernel:

```python
import ast

from papermill.iorw import load_notebook_node
from papermill.execute import _find_first_tagged_cell_index


nb = load_notebook_node('dummy.ipynb')
param_cell_index = _find_first_tagged_cell_index(nb, 'parameters')
param_cell = nb.cells[param_cell_index]

parameters = set()

root = ast.parse(param_cell.source)
for node in root.body:
    if isinstance(node, ast.Assign):
        parameters.update(target.id for target in node.targets)
```

If needed, one could walk the AST and get the values as well, but that's not necessary in my case. I know it's not generic and abuses papermill API, but you might find it useful.

**Comment by MSeal** [comment]
Hello @tlinhart ,

Yes the parameters metadata being read is only the applied parameters from prior papermill runs.

You'll see the AST inspection path was one we were already exploring: https://github.com/nteract/papermill/issues/225. The intention was to create a `papermill input_notebook.ipynb --help` functionality both programmatically and as a command.

Thanks for the code snippet, we'll be exploring completing this idea after the remaining 1.0 features are shipped.

**Comment by tlinhart** [comment]
Thanks @MSeal, I didn't come across that one.
