### ISSUE TITLE
compiling output without recording?

### ISSUE THREAD

**Issue by ironv** [nteract/papermill#310]
I am using papermill to create several datasets based on different input parameters.  Working great.  My setup is nb1 calling nb2 several times using pm.  I would like to capture the output of cell 7 in nb2 and report it all in nb1.  Cell 7 has several filters with print statements which shows counts after the filter is applied.  A painful way to do that may be to use a list to capture all these statements, `pm.record` it and then reproduce it in nb1.  I was hoping there was an easier way to do the same.  Is there?

**Comment by MSeal** [comment]
The limitations of the record functionality is being addressed in https://github.com/nteract/scrapbook (installable as `scrapbook-beta` atm). The intention is to make recording data and recalling it more flexible. There's still some syntax adjustments going on but the initial release should be in the next couple weeks.

That being said, if you're just trying to capture the outputs made in cell 7 (not the actual data), I'd suggest just reading the nbformat notebook object and iterate to the 7th cell and fetch outputs.

Something like this should do the trick.

```
nb = execute_notebook('input_path.ipynb', 'output_path.ipynb', ...)
for output in nb.cells[6].outputs:
  log_output_message(output)
```

```
def log_output_message(output):
    if output.output_type == "stream":
        if output.name == "stdout":
            print("".join(output.text))
        elif output.name == "stderr":
            print("".join(output.text), file=sys.stderr)
    elif "data" in output and "text/plain" in output.data:
        print("".join(output.data['text/plain']))
```

**Comment by MSeal** [comment]
If you wanted to add something like this recall functionality to scrapbook I think it'd made a nice addition to the notebook model object there.

**Comment by ironv** [comment]
Thanks.  Is it possible to search a cell based on a tag?  I would still want the output of the cell but your code above would help with that.  Rather than using `no.cells[6]`, how can I get to the cell based on a tag?

Also would the above approach work if the output of the cell contains a small pandas table, a matplotlib chart and then some text?   Looks like it is text specific?

**Comment by MSeal** [comment]
Sure tags are easy, play with the code I provided and you'll see that the cell object has other attributes like `metadata` to read. I'll leave it to you to find tags within that object.

Without using `pm.display` or (or upcoming scrapbook's glue) copying non-text outputs will be error prone, which is why we provides the abstraction to name display outputs. See https://papermill.readthedocs.io/en/latest/usage-display.html for details of naming display objects.
