### ISSUE TITLE
Example of notebook outbook name from parameters

### ISSUE THREAD

**Issue by thomasworville** [nteract/papermill#311]
Hi, I'm trying to set my notebook output path based on the parameters in my source notebook. 

For example, with the following parameters:
 - company_name
 - year

I'd like to construct the output path as:
notebooks/outputs/{company_name}_{year}.ipynb

Is this possible? I consulted the CLI documentation (https://papermill.readthedocs.io/en/latest/usage-cli.html) and saw the `--inject-output-path` flag, but I'm unsure on how it's used.

**Comment by MSeal** [comment]
So it's a pretty simple addition to papermill already proposed here https://github.com/nteract/papermill/issues/300 if you wanted to contribute the change. For now you have to repeat the interpolation outside of papermill.

```
pm.execute("notebooks/inputs/base.ipynb", "notebooks/outputs/{company_name}_{year}.ipynb".format(company_name, year), {"company": company, "year": year}
```

or in the CLI form, via bash interpolation

**Comment by MSeal** [comment]
The `--inject-output-path` is to indicate if the notebook output path should be injected into parameters, not the other way around.

**Comment by thomasworville** [comment]
Great, thanks a lot for the swift response.
