### ISSUE TITLE
Use pm.record from another notebook

### ISSUE THREAD

**Issue by adace123** [nteract/papermill#314]
I have a case where a function that accepts a key/value pair is being shared across multiple other notebooks. 
Not sure if this is possible, but it would be helpful to be able to record the key/value pair to whatever notebook I specify from within the function. 
Thanks.

**Comment by MSeal** [comment]
Hmm the closest to this would be to execute that notebook with a parameter being passed through with the data you wanted. It would be a bit odd to populate a notebook with outputs it didn't itself generate. If you think there's a good use-case we're not covering for behavior of this kind, let's discuss it in  https://github.com/nteract/scrapbook as that's going to replace the record functionality for papermill 1.0

**Comment by adace123** [comment]
Thanks for your reply.
I don't think that would really work in my case since the function is just a utility function and isn't actually executing any notebooks. That's done from a main controller notebook. Basically, the function's job is to generate a URL from parameters passed in and that URL will get saved for other notebooks to use. 

Not saying it's critical to my application by any means, but it would be nice to be able to not have to call pm.record in each notebook that needs a URL.

**Comment by MSeal** [comment]
So, you could also register a custom python translator which convert particularity parameters into a `.record` call when passed to a notebook.

Extend https://github.com/nteract/papermill/blob/master/papermill/translators.py#L117 and register it for the kernel you're using https://github.com/nteract/papermill/blob/master/papermill/translators.py#L217-L221. It's specific to your infrastructure but you could control data passing in a more fine-grained pattern than the base package provides out of the box.
