### ISSUE TITLE
What's the right way to handle relative paths in a notebook?

### ISSUE THREAD

**Issue by choldgraf** [nteract/papermill#316]
I've got a set of folders like so:

```
./
├── data
│   ├── daily.csv
│   └── teams.csv
├── notebooks
│   └── viz_data.ipynb
└── run_papermill.py
```

My template notebooks are in `notebooks/` and there's a script to run papermill on the notebook in `notebooks/` w/ a bunch of input parameters.

Usually I write this by prototyping the `viz_data.ipynb` notebook on a single parameter, then running the python script.

However, I noticed that if the template notebook uses a relative path as a part of its running, it will error because my working directory is now in `.` instead of `./notebooks`.

I could make sure that I change my working directory to `notebooks/` before running papermill, but I wonder if there's a more recommended way to handle relative paths in papermill. Has anybody experienced this before?

**Comment by MSeal** [comment]
We do have the `--cwd` option when executing which let's papermill know what directory to be in during execution.

**Comment by choldgraf** [comment]
I'm silly, I must have looked at the python docstring a thousand times but totally missed the cwd parameter. thanks for being patient w/ me :-)
