### ISSUE TITLE
How to Run Julia Notebook

### ISSUE THREAD

**Issue by usmcamp0811** [nteract/papermill#318]
I couldn't find any examples on how to run a Notebook in another language, such as Julia. I saw there are some language translator plugins for Julia but I don't full understand how to use it. Can anyone help with an example? Thanks

**Comment by MSeal** [comment]
So notebook documents store the language of the kernel (the repl process that will actually execute the code you're writing). I'd follow https://github.com/JuliaLang/IJulia.jl and edit a notebook with a Julia kernel. The resulting notebook file from editing with a notebook editor like Jupyter Classic or Jupyter Lab can then be executed and parameterized by papermill, which reads the metadata within the resulting document to determine the language.

This library will translate the parameters to a Julia code cell on demand when executing the notebook you crafted. Think of it as a CLI/code interface for executing a document which is normally executed via a user over a web server.

**Comment by usmcamp0811** [comment]
Thanks for the response. I tried it with a simple Hello World notebook where I just passed a singe parameter to be printed and it didn't work. I was using the CLI method for executing the notebook. I'm not in front of the right computer right now so I can't post the exact stuff but it was basically:

`papermill test.ipynb output.ipynb -p say="hello world"`

The notebook was nothing more than the parameter cell and a cell that was `println(say)`. 

I had the kernel set to my Julia kernel. When I opened the output notebook the parameter cell was updated but the code cell was not. I also tried this with a plot to change the number of random points and got some compile error inside the notebook saying it could make the plot.

**Comment by MSeal** [comment]
The code cell should not change, only a new injected parameter cell. I didn't write the Julia translator so I haven't validated there aren't translation issues myself. Can you post simple versions of the notebooks you were trying to use? I can verify behavior and maybe suggest how to fix on your end or ours.

**Comment by usmcamp0811** [comment]
My test cases are [here](https://gist.github.com/usmcamp0811/78cc7fb369a3ba3a19d6ea2ab515733c). Thanks for taking a look.

**Comment by MSeal** [comment]
Ahh so you'll want to tag the cell with your default parameters via https://github.com/nteract/papermill/blob/master/docs/img/enable_parameters.gif . The parameters are being applied to the top of the file because it couldn't find any cell tagged to choose an injection location. Then the cell that has your parameters will be placed below the cell with defaults.
