### ISSUE TITLE
Plugin 'jupyterlab-celltags' failed to activate.

### ISSUE THREAD

**Issue by rekham23** [nteract/papermill#327]
Installed JupyterLab v1.0.0a1
Installed Jupyterlab celltag extension , celltags v0.1.4 

I am getting error Plugin 'jupyterlab-celltags' failed to activate.
I couldn't see the 'Add Tag' in Tools.

jupyterlab-celltags extension is not compatible with latest JupyterLab v1.0.0a1

Please look into the issue.

**Comment by MSeal** [comment]
This should really be a jupyterlab GitHub issue. I'd ask in that project as it's mostly unrelated to papermill as described.

**Comment by rekham23** [comment]
Is this fixed in latest jupyterlab

**Comment by MSeal** [comment]
I have no idea. It's just not a papermill issue and there was no response for 10 days here so I closed the ticket. I'd create or find an existing issue on jupyterlab's github page to help resolve your plugin issue.

**Comment by rekham23** [comment]
Can you please suggest if any alternative way to add tags in the latest jupyterlab

**Comment by MSeal** [comment]
I believe https://github.com/jupyterlab/jupyterlab-celltags is still the prescribed manner to set cell tags in lab. If you have opened an issue and really need to edit cell tags, you can temporarily load the notebook in classic use https://github.com/nteract/papermill#parameterizing-a-notebook to save a notebook outside of lab with the tag.
