### ISSUE TITLE
Make Custom Preprocessor for papermill

### ISSUE THREAD

**Issue by ewmassey** [nteract/papermill#33]
We are currently monkey patching the preprocessor in the execute.py module. We should be using subclassing the Preprocessor class as intended.

https://github.com/nteract/papermill/blob/master/papermill/execute.py#L22

**Comment by ewmassey** [comment]
@mpacer

**Comment by MSeal** [comment]
This should be fixed by https://github.com/nteract/papermill/pull/136 -- didn't see we had duplicate issues on the subject. Will close once we merge the PR
