### ISSUE TITLE
pm.execute_notebook not raising error when a cell has failed.

### ISSUE THREAD

**Issue by mbrio** [nteract/papermill#330]
I've been working with Papermill, Airflow, and SparkMagic and have found that when a cell fails, even after the entire notebook has completed running, it does not raise an error. Usually an Airflow DAG will error out if a python script run from PythonOperator raises an error. This never happens in my DAGs that use Papermill because Papermill is not raising an error. I looked at the output of the notebook and I am seeing red boxes saying an error has occurred, but unfortunately the metadata is showing a success on Papermill. I am using a standard Python function that calls:

```python
pm.execute_notebook(
        notebook_path,
        out_path,
        parameters=statement_parameters
    )
```

**Comment by MSeal** [comment]
So this is likely a kernel issue. There are some kernel that do not follow the kernel spec completely. What kernel, papermill, nbconvert, and python versions are you seeing the issue with?

**Comment by mbrio** [comment]
Kernel: PySpark3 from sparkmagic
Papermill: 0.19.0
nbconvert: 5.4.0
python: 3.6.5

**Comment by mbrio** [comment]
I dug a little deeper and found that the output_type for the error from sparkmagic is stderr, I was trying to find protocol information on errors on the ipython codebase but couldn't find it. If there are specific guidelines, could you point me to them so that I can bring this up to the sparkmagic developers (or help fix the problem if I can).

**Comment by MSeal** [comment]
Sorry for the slow responses, I was traveling and am catching up on notification now.

Yes, this is a similar problem to the Toree kernel. The output type should be `"error"` when an error occurs. Usually this is sent right after the `"stderr"` messages. This is a fallback for the true behavior which should be that the kernel message (not the outputs itself) should have `reply['content']['status'] == 'error'` be true for the error over the zeromq bus.

I'll comment on your issue in that project, it really is dependent on the kernel to tell papermill there was an error. It can't interpret stack traces in stderr as failures.

**Comment by mbrio** [comment]
As this is an issue with SparkMagic and not Papermill, I will close this issue.
