### ISSUE TITLE
Writing to /dev/null from CLI results in warnings

### ISSUE THREAD

**Issue by zachwill** [nteract/papermill#335]
Big fan of papermill!

I'm currently using it to run Jupyter notebooks from the command line. Here's a quick example:

`papermill --log-output test.ipynb /dev/null`

This results in warnings on a missing file extension. Code in question here: https://github.com/nteract/papermill/blob/59641ed4dc45a883ff21692fd2781d8d628ce1dd/papermill/iorw.py#L99-L109

I'm wondering if there should just be a `/dev/null` check before raising the warning? (Kind of a tangential issue to #107 that allows the user to deal with the execution result.)

Thanks!

**Comment by MSeal** [comment]
Hmm, hard to say if we should treat `/dev/null` specially. I kind of like that it warns you that it's not saving to an ipynb file in this case. If you used a default variable which got assigned to the null path I'd want to know it was doing so in the logs. If you want we could add a different warning for `/dev/null` in the code you referenced above? Thoughts?

**Comment by zachwill** [comment]
I can see a case to be made to not specifically check for `/dev/null`. Thoughts on maybe a CLI option to suppress warnings then?

**Comment by MSeal** [comment]
So you can set `--log-level` to silence warnings today. I'm torn on making a new option just for this one warning, is `--log-level` sufficient? Trying to KISS the interface when possible.

**Comment by zachwill** [comment]
Makes sense. I think `--log-level` is sufficient 👍

**Comment by hevansDev** [comment]
I'm having the same issue and setting log level to error isn't suppressing the warning

```
papermill ../$file /dev/null --execution-timeout=1200 --log-level ERROR
```

Results in 

```
Executing:   0%|          | 0/61 [00:00<?, ?cell/s]/opt/conda/lib/python3.11/site-packages/papermill/iorw.py:149: UserWarning: the file is not specified with any extension : null
  warnings.warn(f"the file is not specified with any extension : {os.path.basename(path)}")
/opt/conda/lib/python3.[11](https://github.com/implydata/learn-druid/actions/runs/10830386668/job/30050039669#step:5:12)/site-packages/papermill/iorw.py:149: UserWarning: the file is not specified with any extension : null
  warnings.warn(f"the file is not specified with any extension : {os.path.basename(path)}")
/opt/conda/lib/python3.11/site-packages/papermill/iorw.py:149: UserWarning: the file is not specified with any extension : null
  warnings.warn(f"the file is not specified with any extension : {os.path.basename(path)}")
Executing:   2%|▏         | 1/61 [00:00<00:53,  1.[13](https://github.com/implydata/learn-druid/actions/runs/10830386668/job/30050039669#step:5:14)cell/s]/opt/conda/lib/python3.11/site-packages/papermill/iorw.py:149: UserWarning: the file is not specified with any extension : null
  warnings.warn(f"the file is not specified with any extension : {os.path.basename(path)}")
  ```
