### ISSUE TITLE
How to change which jupyter executed installed?

### ISSUE THREAD

**Issue by halilduygulu** [nteract/papermill#346]
Hi, thanks for this great project. 
I have a question that I could not figure out by reading the code. Basically I am trying to run papermill in the AWS Sagemaker instance and it only runs the default kernel because jupyter executable sees that location. Then I got sklearn not found errors even if I specifiy --kernel for papermill correctly. 

Do you know if I can force papermill to use a jupyter in a specific path if there are multiple jupyters installed?

>sh-4.2$ which jupyter
/home/ec2-user/anaconda3/envs/JupyterSystemEnv/bin/jupyter 
sh-4.2$ find . -name jupyter
./.cache/yarn/v2/npm-@jupyterlab/theming-0.9.0-7c165542d60ee3d2e266cc596e5aae1a100387b3/style/icons/jupyter
find: ./SageMaker/lost+found': Permission denied
./.local/share/jupyter
./anaconda2/share/jupyter
./anaconda2/bin/jupyter
./anaconda2/etc/jupyter
./anaconda2/pkgs/widgetsnbextension-3.2.1-py27_0/share/jupyter
./anaconda2/pkgs/widgetsnbextension-3.2.1-py27_0/etc/jupyter
./anaconda2/pkgs/ipykernel-4.8.2-py27_0/share/jupyter
./anaconda2/pkgs/_ipyw_jlab_nb_ext_conf-0.1.0-py27h08a7f0c_0/etc/jupyter
./anaconda2/pkgs/jupyter_core-4.4.0-py27h345911c_0/bin/jupyter
./anaconda2/pkgs/jupyterlab-0.32.1-py27_0/share/jupyter
./anaconda2/pkgs/jupyterlab-0.32.1-py27_0/etc/jupyter
./anaconda3/share/jupyter
./anaconda3/bin/jupyter
./anaconda3/envs/pytorch_p27/share/jupyter
./anaconda3/envs/pytorch_p27/bin/jupyter
./anaconda3/envs/pytorch_p27/etc/jupyter
./anaconda3/envs/pytorch_p36/share/jupyter
./anaconda3/envs/pytorch_p36/bin/jupyter
./anaconda3/envs/pytorch_p36/etc/jupyter
./anaconda3/envs/amazonei_mxnet_p27/share/jupyter
./anaconda3/envs/amazonei_mxnet_p27/bin/jupyter
./anaconda3/envs/amazonei_mxnet_p27/etc/jupyter
./anaconda3/envs/mxnet_p27/share/jupyter
./anaconda3/envs/mxnet_p27/bin/jupyter
./anaconda3/envs/mxnet_p27/etc/jupyter
./anaconda3/envs/tensorflow_p27/share/jupyter
./anaconda3/envs/tensorflow_p27/bin/jupyter
./anaconda3/envs/tensorflow_p27/etc/jupyter
./anaconda3/envs/JupyterSystemEnv/share/jupyter
./anaconda3/envs/JupyterSystemEnv/share/jupyter/lab/staging/node_modules/@jupyterlab/theming/style/icons/jupyter
./anaconda3/envs/JupyterSystemEnv/bin/jupyter
./anaconda3/envs/JupyterSystemEnv/etc/jupyter
./anaconda3/envs/chainer_p27/share/jupyter
./anaconda3/envs/chainer_p27/bin/jupyter
./anaconda3/envs/chainer_p27/etc/jupyter
./anaconda3/envs/tensorflow_p36/share/jupyter
./anaconda3/envs/tensorflow_p36/bin/jupyter
./anaconda3/envs/tensorflow_p36/etc/jupyter
./anaconda3/envs/python3/share/jupyter
./anaconda3/envs/python3/bin/jupyter
./anaconda3/envs/python3/etc/jupyter
./anaconda3/envs/amazonei_tensorflow_p36/share/jupyter
./anaconda3/envs/amazonei_tensorflow_p36/bin/jupyter
./anaconda3/envs/amazonei_tensorflow_p36/etc/jupyter
./anaconda3/envs/amazonei_mxnet_p36/share/jupyter
./anaconda3/envs/amazonei_mxnet_p36/bin/jupyter
./anaconda3/envs/amazonei_mxnet_p36/etc/jupyter
./anaconda3/envs/chainer_p36/share/jupyter
./anaconda3/envs/chainer_p36/bin/jupyter
./anaconda3/envs/chainer_p36/etc/jupyter
./anaconda3/envs/python2/share/jupyter
./anaconda3/envs/python2/bin/jupyter
./anaconda3/envs/python2/etc/jupyter
./anaconda3/envs/amazonei_tensorflow_p27/share/jupyter
./anaconda3/envs/amazonei_tensorflow_p27/bin/jupyter
./anaconda3/envs/amazonei_tensorflow_p27/etc/jupyter
./anaconda3/envs/mxnet_p36/share/jupyter
./anaconda3/envs/mxnet_p36/bin/jupyter
./anaconda3/envs/mxnet_p36/etc/jupyter
./anaconda3/etc/jupyter
./anaconda3/pkgs/jupyter_core-4.4.0-py36h7c827e3_0/bin/jupyter
./anaconda3/pkgs/jupyter_core-4.4.0-py36_0/bin/jupyter
./anaconda3/pkgs/nb_conda-2.2.1-py35_0/share/jupyter
./anaconda3/pkgs/nb_conda-2.2.1-py27_2/share/jupyter
./anaconda3/pkgs/widgetsnbextension-3.4.2-py36_0/share/jupyter
./anaconda3/pkgs/widgetsnbextension-3.4.2-py36_0/etc/jupyter
./anaconda3/pkgs/jupyterlab-0.32.1-py36_0/share/jupyter
./anaconda3/pkgs/jupyterlab-0.32.1-py36_0/etc/jupyter
./anaconda3/pkgs/nb_conda-2.2.1-py36_2/share/jupyter
./anaconda3/pkgs/ipykernel-5.1.0-pyh24bf2e0_0/share/jupyter
./anaconda3/pkgs/ipykernel-4.8.2-py36_0/share/jupyter
./anaconda3/pkgs/plotly-3.7.1-py_0/share/jupyter
./anaconda3/pkgs/plotly-3.7.1-py_0/etc/jupyter
./anaconda3/pkgs/_ipyw_jlab_nb_ext_conf-0.1.0-py36he11e457_0/etc/jupyter
./anaconda3/pkgs/ipykernel-5.1.0-py36h39e3cac_0/share/jupyter

**Comment by MSeal** [comment]
This actually has more to do with what kernels + papermill are installed to particular python environments. Basically when you're executing papermill / jupyter you're in one of those environments (the `bin/` directory is in the root of those environments). Activating an environment adds both python packages and cli interfaces to the current context. From your list you have `anaconda2` and each of the directory names under `anaonda3/envs`.

For `conda` https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#activating-an-environment has good guidance for how to select your environment. You'd need to activate the environment with the dependencies you want -- or install into that environment -- including papermill. Then you'll be using the dependencies of that environment, including the kernels which you need for execution.

**Comment by halilduygulu** [comment]
Hi Matthew, thank you for your response. I was indeed running papermill from default environment because yesterday I installed papermill and then started to switching between enviroments instead of installing papermill inside each environment. 

Thanks your advice, it works now. I will close this issue now as it was my lack of knowledge. 
Great job with this project, kudos again.
