### ISSUE TITLE
mybinder.org build broken because of setup.py and pyproject.toml presence

### ISSUE THREAD

**Issue by betatim** [nteract/papermill#348]
The build on mybinder.org (via repo2docker) is broken :-(

The error I see is:

> ERROR: Error installing 'file:///home/jovyan (from -r binder/requirements.txt (line 1))': editable mode is not supported for pyproject.toml-style projects. pip is processing this project as pyproject.toml-style because it has a pyproject.toml file. Since the project has a setup.py and the pyproject.toml has no "build-backend" key for the "build_system" value, you may pass --no-use-pep517 to opt out of pyproject.toml-style processing. See PEP 517 for details on pyproject.toml-style projects.

I think this broke when we upgraded repo2docker to use a modern version of pip (v19.0.3 or some such), before it was v18.

Maybe now there is a 1.0.0 release we can install from PyPI instead of from the repo? Or figure out what additional arguments need passing to `pip` to sort out the competition between `setup.py` and `pyproject.toml`.

**Comment by MSeal** [comment]
Yea I just noticed this today and was looking at we might fix it. I think the main issue is our pyproject.toml needs to be updated. I'm gonna try it out and see.
