### ISSUE TITLE
Provide a list parameter in the command line

### ISSUE THREAD

**Issue by Ezibenroc** [nteract/papermill#363]
I would like to pass a list as parameter value.
Currently, this can be done with a yaml file:
```yaml
my_list:
    - abc
    - def
    - ghi
```
Or the yaml code can be passed in the command line:
```shell
papermill input.ipynb output.ipynb -y '{my_list:[abc,def,ghi]}'
```
However, I would like to achieve such behavior with something like this (a list of values separated by spaces):
```shell
papermill input.ipynb output.ipynb -p my_list abc def ghi
```

----

My use case is that I often have notebooks that load a bunch of CSV files into a large pandas dataframe. I would like to use file globbing like this:
```shell
papermill input.ipynb output.ipynb -p my_files some/path/*.csv another/path/*.csv
```

**Comment by MSeal** [comment]
That sounds convenient. I'm not 100% sure how to make click allow for 1-* values for a key, but I'm sure it'd be possible to add with a little exploration.

**Comment by MSeal** [comment]
Closing this issue as a won't-do scenario, see #441 for details.

**Comment by sumitbinnani** [comment]
@MSeal now that we have "-r" as an option, is list supported for CLI?
