### ISSUE TITLE
Move the "ipython" requirement to requirements-dev.txt

### ISSUE THREAD

**Issue by tsvikas** [nteract/papermill#370]
I believe that, to load, change, execute & save jupyter notebooks, the dependency on `ipython` is unnecessary.

In my checks, `nbformat`, `nbconvert` & `jupyter_client` are required, but `ipython` is not. Since this package has a bunch of dependencies itself, removing it will allow much leaner dependency tree.

However, some of the notebooks that are used in the tests are importing `IPython`, so they need to run in an environment that contains `ipython`. As far as I know, the best practice to do that is to add `ipython` to `requirement-dev.txt` (alternatively, to create an optional extra dependency `papermill[tests]`, or to remove `IPython` from the test notebooks).

**Comment by MSeal** [comment]
Good call, yes that's a preferable change.
