### ISSUE TITLE
How to parameterise a Python dictionary in papermill?

### ISSUE THREAD

**Issue by avisrivastava254084** [nteract/papermill#371]
I want to pass on all the parameters in one variable. To make this happen, I am passing a dictionary in my Python client for Papermill using:
```
params = {"aviral":"srivastava"}
pm.execute_notebook( 'path/to/input.ipynb', 'path/to/output.ipynb', parameters = params )
```

Now, I want to do run the corresponding command from bash. In the [document](https://github.com/nteract/papermill) it states: 
```
papermill local/input.ipynb s3://bkt/output.ipynb -p alpha 0.6 -p l1_ratio 0.1
```
But nowhere is given how to pass on a dictionary.

I tried many permutations and combinations like:

```papermill test_params.ipynb params_output.ipynb -p params {"aviral":"srivastava"}```

```papermill test_params.ipynb params_output.ipynb -p params '{"aviral":"srivastava"}'```

I also read to pass a `dict` in the format: `'{"aviral":"srivastava"}'` and then json.loads would do the work. But I am not having the liberty for converting the input. It has to be used right away in the script.

Just a minimal script to actually check the type of the variable passed:
```
params = {} # I tag this with `parameter`
print(type(params))
print(params)
```

Yes, I see the params variable got changed when running with papermill but the value passed is a complete string.

**Comment by MSeal** [comment]
`-y '{"aviral":"srivastava"}'` Since yaml is a superset of json

**Comment by avisrivastava254084** [comment]
While running the command:
```
papermill athena-py/params_to_dict.ipynb athena-py/output_params_to_dict.ipynb -p params '{"testyaml":"yaml tested"}'
```
worked as I used the convert_to_dict function of mine.
the following command failed:
```
papermill athena-py/params_to_dict.ipynb athena-py/output_params_to_dict.ipynb -y '{"testyaml":"yaml tested"}'
```

I am able to see that the parameters have been passed in the `papermill` section of the output script but not to the variable as I went through the output of the script.

**Comment by MSeal** [comment]
I'm not sure I follow. Your description of results is confusing me. Running `-y '{"testyaml":"yaml tested"}'` produces

![yaml_input](https://user-images.githubusercontent.com/1863892/58577249-ed9ff100-81fa-11e9-84cf-3fe1c86802df.png)

which is the same as passing `params = {"testyaml": "yaml tested"}` in python.

**Comment by avisrivastava254084** [comment]
Apologies for such a late reply, will make sure that from now, I am active and respond right away.
Also, I cracked the params stuff, I was confused before, my bad.

On this note, thanks a lot @MSeal for always responding back here.

**Comment by MSeal** [comment]
Glad to hear you got it worked out :)
