### ISSUE TITLE
Allow accepting notebooks on stdin

### ISSUE THREAD

**Issue by rgbkrk** [nteract/papermill#372]
As mentioned in #243, it would be nice to be able to pipe a notebook to papermill by allowing input on stdin. Use case:

```
$ someCommand | papermill - s3://location/
```

This is [fairly common in *nix land to use `-` to denote stdin as the input file](https://unix.stackexchange.com/a/16364). 

cc @mwouts

**Comment by rgbkrk** [comment]
Note: one workaround that might work for folks is using `/dev/stdin` like this:

```
$ someCommand | papermill /dev/stdin someFile.ipynb
```

**Comment by rgbkrk** [comment]
Oh nevermind, that doesn't work due to extension checking:

```
/Users/kylek/miniconda3/lib/python3.7/site-packages/papermill/iorw.py:86: UserWarning: the file is not specified with any extension : stdin
  "the file is not specified with any extension : " + os.path.basename(path)
```

**Comment by MSeal** [comment]
The work-around does actually work -- that's only a warning rather than an actual error.

I do agree we should properly solve for stdin as a convenience. Though I'd prefer `someCommand | papermill s3://output/location` with the `-` as optional.

**Comment by rgbkrk** [comment]
Oh I see, I was running into a different error afterward:

```
curl https://raw.githubusercontent.com/jupyter/nbformat/master/nbformat/tests/test2.ipynb | papermill /dev/stdin ./test3.ipynb -k python
```

Yes, I see I'm doing something just as bad as piping a curled script to bash. 😆  That's not what the stdin was for though. 😛

**Comment by mwouts** [comment]
Yes, piping notebooks into `papermill` would be great!
By the way, maybe this is the best way to solve #365 (Run Papermill on Jupytext notebooks). 

Also (possibly this is not the right place to discuss this), I would sometime appreciate to get the executed notebook on stdout and pipe it into over tools. Sometimes I do not want to give a name to the executed notebook, e.g. if I want to run `nbconvert --to html` and only store the resulting html file. As @rgbkrk noticed however, outputting the notebook on stdout would required to deactivate the logs, but I think I've seen an option for that already, right?

**Comment by rgbkrk** [comment]
Done in #373
