### ISSUE TITLE
ImportError when Running Code off python.exe

### ISSUE THREAD

**Issue by GXAB** [nteract/papermill#379]
Hi,
When I run the following code it does as intended.
```
import papermill as pm
pm.execute_notebook('test.ipynb',
                    'test.ipynb',
                    parameters=dict())
```
However if I run the code off cmd like so:
`C:\Users\me> python.exe code_above.py`
I get
```
raise ImportError: 'nbconvert --execute' requires the jupyter_client package: 'pip install jupyter_client'
```
So went to install the client but it was already installed in my environment. I uninstalled and reinstalled with the same error.
The reason why I need python.exe to run it is because I am hoping to put it in windows scheduler.

Any help is appreciated.

Thanks.

**Comment by MSeal** [comment]
Likely your python.exe is referencing a different python than the one where you installed the dependencies. This happens a lot in windows setups. Two things you can do.

First, you can use virtual environments following [these instructions](https://docs.python.org/3/library/venv.html) to make sure your python dependencies are installing into the same environment that you're executing with.

And second papermill actually has a [command line interface](https://papermill.readthedocs.io/en/latest/usage-cli.html) so all you need to do after installing is call `papermill test.ipynb test-out.ipynb -p foo bar`

**Comment by MSeal** [comment]
Going to close this issue as it sounds resolved or at least no comment has been made that it's beyond the scope of the proposed solutions.
