### ISSUE TITLE
missing documentation for conda kernels

### ISSUE THREAD

**Issue by casperdcl** [nteract/papermill#382]
related to #251/#366, the documentation (https://papermill.readthedocs.io/en/latest/troubleshooting.html) also needs to reference jupyter/jupyter/issues/245 i.e.

```bash
source activate analysis_1
python -m ipykernel install --user --name analysis_1  # <--- this should be in the docs
papermill ... -k analysis_1
```

**Comment by MSeal** [comment]
Good catch. If you wanted to make a PR to the doc/ file for this I'd gladly merge it.

**Comment by casperdcl** [comment]
right. might need a little more than just the one line now I come to think about it; will do
