### ISSUE TITLE
Missing instructions for JupyterLab usage

### ISSUE THREAD

**Issue by duarteocarmo** [nteract/papermill#386]
I think we could add an explanation on how to add tags in JupyterLab. 

This could be particularly useful for folks now moving to it. 

For your reference, this is done by editing the metadata section in JupyterLab: 

![image](https://user-images.githubusercontent.com/26342344/60173245-93e91180-980e-11e9-8c0a-82b2c8ab5e53.png)

I suggest we add a note in the documentation. What do you think?

**Comment by rgbkrk** [comment]
We'd love that addition to the documentation!

**Comment by duarteocarmo** [comment]
Will make a pull request

**Comment by duarteocarmo** [comment]
@rgbkrk  just to confirm, since there is no particular documentation specific to contributing to docs. 

My guess is I can clone repo and follow [this](https://travis-ci.org/nteract/papermill/jobs/550623562)?

basically run 
```bash
$ tox -e docs
```
right?

**Comment by rgbkrk** [comment]
Yeah, let me know how that goes and perhaps you can also [add a section to `CONTRIBUTING.md` for docs](https://github.com/nteract/papermill/blob/master/CONTRIBUTING.md).

**Comment by duarteocarmo** [comment]
Just a note, after installing the environment specified by doing `conda create -n dev`, and trying to preview the `.rst` files, the [`recommonmark`](https://pypi.org/project/recommonmark/) package was missing. (it's imported over at [`conf.py`](https://github.com/nteract/papermill/blob/master/docs/conf.py#L25))

**Comment by rgbkrk** [comment]
Hmmm, seems we need it added to https://github.com/nteract/papermill/blob/master/requirements-dev.txt

**Comment by duarteocarmo** [comment]
Just created a first pull request with the parameterization instructions, what do you think?

**Comment by duarteocarmo** [comment]
@rgbkrk I also added a section on how to generate docs and test them. See #390 😄 

Going to sleep now, I'm all done. Cool project btw, great work
