### ISSUE TITLE
papermill CLI executing notebooks exception message return to parent process

### ISSUE THREAD

**Issue by vinaykumar80** [nteract/papermill#407]
Hi All,

Wanted to know if papermill CLI can capture exception message on encountering an error within a notebook execution and send this message back to parent process? (Python script using subprocess to call papermill CLI to execute notebook)

I am currently capturing Zero (Success) or Non-zero (Failure) return code on papermill command execution, but exception message on error would be useful for debugging and to store as Failure reason in execution metadata store.

Please let me know if additional details are needed

Thanks!

**Comment by MSeal** [comment]
The `PapermillExecutionError` that raises to change the exit code has most of what you're asking for: https://github.com/nteract/papermill/blob/master/papermill/execute.py#L167-L173

This information is also stored in the notebook metadata.

**Comment by vinaykumar80** [comment]
Sounds good, Thank you!
