### ISSUE TITLE
Running papermill inside of virtual environment

### ISSUE THREAD

**Issue by treuning** [nteract/papermill#408]
I am trying to run papermill inside of a virtual environment that contains a React webapp and a Python server. I have pip'd papermill into the environment. I am able to run papermill but it errors out on the first import statement importing a custom module:

```
ImportError                               Traceback (most recent call last)
<ipython-input-1-ef3f079b4cf7> in <module>()
----> 1 from toolkit import tools
      2 
      3 #STATIC VARIABLES
      4 BASE_URL = "http://localhost:8080"
      5 USER_ID = 'admin'

```
ImportError: No module named toolkit

I saw [Issue 251](https://github.com/nteract/papermill/issues/251) but I am not running conda.

**Comment by MSeal** [comment]
You should check that your kernel is running in the correct virtual environment. The initial comments to #251 still applies outside of a conda environment. How are you installing the kernels, and what OS / environment setup do you have? Likely your accessing some global python for the kernel outside of your virtual env.

**Comment by treuning** [comment]
I was running in the wrong base directory, works now. Awesome tool!
