### ISSUE TITLE
Question:  Is there a flag to not preserve the injected-parameters cell in the output Notebook?

### ISSUE THREAD

**Issue by rwmajor2** [nteract/papermill#416]
Passing parameters is extremely useful.  However, if users are passing passwords or sensitive information, this information may not want to be preserved in the output Notebook.  Are there any flags or ideas on how to overcome this?

My initial thought is to interrogate the output Notebook (using JSON) and remove the cell with the injected-parameters tag.

**Comment by MSeal** [comment]
The short answer is no, there's not a flag. But there's ways to achieve what you want.

The thing is you probably shouldn't pass unencrypted secrets to a notebook. Pass encrypted secrets and decrypt to memory during execution. Additionally, never print the decrypted result. The parameters also get saved in the metadata of the notebook, and the kernel could leak or save the code it's executing easily as well (with older nbconvert ipykernels were saving every command to sqllite).

That being said, if you wanted to remove the injected cell you could pass the resulting notebook through nbconvert's TagRemovePreprocessor `jupyter nbconvert --TagRemovePreprocessor.remove_cell_tags="['injected-parameters']" papermill_output.ipynb`. You'd also still need to remove the papermill metadata in the json document which stores the parameters as well if you were trying to hide the inputs.

**Comment by rwmajor2** [comment]
@MSeal Thanks.  Good suggestions.
