### ISSUE TITLE
Typo in anti-flag for `--report-mode`

### ISSUE THREAD

**Issue by akx** [nteract/papermill#421]
There's a simple typo in the definition of `--report-mode`:

https://github.com/nteract/papermill/blob/01ec212f14c76860f3788f6f92f9be27d5742ea3/papermill/cli.py#L150

All other flag values have an "anti-flag" of `--no-something`, `--report-mode` has `--not-report-mode` (_not_ vs _no_).

**Comment by MSeal** [comment]
Seems fair. Want to submit a patch to change the argument?
