### ISSUE TITLE
a good way to early stop the script

### ISSUE THREAD

**Issue by juancrescente** [nteract/papermill#435]
Hi!

is there a way to "exit" the execution properly?
sys.exit() throws an exception

**Comment by MSeal** [comment]
Unfortunately no. The default `exit` and `quit` magics only (sorta) work with a javascript execution engine. Though I think this would be a pretty easy thing to patch in papermill. Here's the output we collect from the kernel, which indicates that a `SystemExit` exit occured with an `evalue` of `0`. We could use this to set the exit status of papermill (an exit of status 0 should probably not throw an exception in papermill).

```
   "outputs": [
    {
     "ename": "SystemExit",
     "evalue": "0",
     "output_type": "error",
     "traceback": [
      "An exception has occurred, use %tb to see the full traceback.\n",
      "\u001b[1;31mSystemExit\u001b[0m\u001b[1;31m:\u001b[0m 0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\users\\mseal\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\IPython\\core\\interactiveshell.py:3334: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.\n",
      "  warn(\"To exit: use 'exit', 'quit', or Ctrl-D.\", stacklevel=1)\n"
     ]
    }
   ],
   "source": [
    "sys.exit(0)"
   ]
```
