### ISSUE TITLE
PrettyPrint parameters

### ISSUE THREAD

**Issue by MSeal** [nteract/papermill#436]
When we inject parameters they form very large single lines if the parameter is a map or list of arguments. It's be nice for readability if the parameter injection was smart about formatting inputs and ran them through a linter or printed maps / lists in a way that was more legible. This might become language / kernel specific, but would still be a solid improvement to generated notebooks.

**Comment by petebachant** [comment]
Seconded. We will sometimes add a somewhat large dictionary as a parameter, and it would be nice if it were formatted with hanging indents, i.e.,

```python
my_dict = {
    "something": 5
}
```

instead of 

```python
my_dict = {"something": 5}
```

Maybe make use of the [black](https://github.com/psf/black) automatic code formatting package for writing the parameters cell?

**Comment by MSeal** [comment]
Yes, likely we'd move to using black in the python language translator -- meaning it would only work for python code. One of the constraints to doing this before was the fact papermill runs in python 2 and 3 and black is python 3 only. But the next release will constraint papermill to python 3 only, meaning we could more easily integrate this pattern.

**Comment by MSeal** [comment]
If you wanted to take a crack at adding the PR I'd gladly help get it reviewed / merged :D

**Comment by petebachant** [comment]
Any hints on where this happens in the codebase?

**Comment by petebachant** [comment]
Never mind. Think I found it.
