### ISSUE TITLE
Problem when setting output_path as GCS address

### ISSUE THREAD

**Issue by AyatoKamina** [nteract/papermill#445]
Hi, I am trying to use papermill to read a notebook from GCS as well as use a GCS location as the output_path.

When I set input_path to a notebook in GCS it works just fine as long as I have output_path set to a local directory, however, if I set both input_path and output_path to a GCS location/file then I get this error.

I am running a papermill function through a DAG within airflow using the PythonOperator.

My code to call papermill looks like so - 

>pm.execute_notebook(
>        input_notebook,
>        output_notebook,
>        parameters=statement_parameters
>    )

and the args I am passing in for use there are - 

>input_notebook': 'gs://ml_notebooks/hello-world.ipynb',
>            'output_notebook': 'gs://ml_notebooks/output/output.ipynb',
>            'statement_parameters': {
>                'msgs': ["Hello World!"]
>            }

When I run the DAG through airflow, it prints out the correct parameters like so - 

> [2019-11-15 13:47:21,776] {execute.py:73} INFO - Input Notebook:  gs://ml_notebooks/hello-world.ipynb
> [2019-11-15 13:47:21,776] {execute.py:74} INFO - Output Notebook: gs://ml_notebooks/output/output.ipynb`

however then it hits the following error 

>[2019-11-15 13:47:23,975] {taskinstance.py:1089} INFO - Marking task as FAILED.
>Traceback (most recent call last):
>  File "/usr/local/bin/airflow", line 37, in <module>
>    args.func(args)
>  File "/usr/local/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
>    return f(*args, **kwargs)
>  File "/usr/local/lib/python3.7/site-packages/airflow/bin/cli.py", line 688, in test
>    ti.run(ignore_task_deps=True, ignore_ti_state=True, test_mode=True)
>  File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
>    return func(*args, **kwargs)
>  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1020, in run
>    session=session)
>  File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 70, in wrapper
>    return func(*args, **kwargs)
>  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 930, in >_run_raw_task
>    result = task_copy.execute(context=context)
>  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in >execute
>    return_value = self.execute_callable()
>  File "/usr/local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in >execute_callable
>    return self.python_callable(*self.op_args, **self.op_kwargs)
>  File "/Users/wxh1ang/workspace/airflow/dags/executenotebookinairflowtest.py", line 24, in >execute_python_notebook_task
>    parameters=statement_parameters
>  File "/usr/local/lib/python3.7/site-packages/papermill/execute.py", line 104, in execute_notebook
>    **engine_kwargs
>  File "/usr/local/lib/python3.7/site-packages/papermill/engines.py", line 49, in >execute_notebook_with_engine
>    return self.get_engine(engine_name).execute_notebook(nb, kernel_name, **kwargs)
>  File "/usr/local/lib/python3.7/site-packages/papermill/engines.py", line 302, in execute_notebook
>    nb_man.notebook_start()
>  File "/usr/local/lib/python3.7/site-packages/papermill/engines.py", line 69, in wrapper
>    return func(self, *args, **kwargs)
>  File "/usr/local/lib/python3.7/site-packages/papermill/engines.py", line 170, in notebook_start
>    self.save()
>  File "/usr/local/lib/python3.7/site-packages/papermill/engines.py", line 69, in wrapper
>    return func(self, *args, **kwargs)
>  File "/usr/local/lib/python3.7/site-packages/papermill/engines.py", line 134, in save
>    write_ipynb(self.nb, self.output_path)
>  File "/usr/local/lib/python3.7/site-packages/papermill/iorw.py", line 365, in write_ipynb
>    papermill_io.write(nbformat.writes(nb), path)
>  File "/usr/local/lib/python3.7/site-packages/papermill/iorw.py", line 121, in write
>    return self.get_handler(path).write(buf, path)
>  File "/usr/local/lib/python3.7/site-packages/papermill/iorw.py", line 309, in write
>    multiplier=self.RETRY_MULTIPLIER, min=self.RETRY_DELAY, max=self.RETRY_MAX_DELAY
> TypeError: __init__() got an unexpected keyword argument 'min'`

I cannot figure out why this is happening, and it seems that min argument has been there as far back as the 1.0.0 papermill version, so I am pretty confused. Also, like I said, I can read notebooks from GCS but when I put a GCS location as output path I get that error.  But if I name the output_notebook to the same thing just in a local location it works.

Any help is appreciated.

**Comment by AyatoKamina** [comment]
@MSeal sorry to bug you but just wondering if you had any insight into this or are you not familiar with the GCS functionality?

**Comment by TPapajCin** [comment]
Hello, I also had this problem, I solved this problem by upgrading **tenacity** package. The error came from **wait_exponential** which is a part of that package so it was worth trying to install different version of it.
`pip3 install --upgrade tenacity`
Command above installed much newer version:
```
Collecting tenacity
  Downloading https://files.pythonhosted.org/packages/bf/d4/8cab4b5239ddb62d950243abff9e88046bb61737ce3eee8694b3d748560c/tenacity-6.0.0-py2.py3-none-any.whl
Collecting six>=1.9.0 (from tenacity)
  Downloading https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl
Installing collected packages: six, tenacity
  Found existing installation: six 1.12.0
    Uninstalling six-1.12.0:
      Successfully uninstalled six-1.12.0
  Found existing installation: tenacity 4.12.0
    Uninstalling tenacity-4.12.0:
      Successfully uninstalled tenacity-4.12.0
```
After that I could successfully save outputs to GCS.

**Comment by MSeal** [comment]
Sorry I wasn't attentive to this thread. I tend to only use this GCS functionality to help debug issues for people using papermill so I'm usually not the first person to notice the upstream dependencies changed or are having other issues. @AyatoKamina can you confirm the fix solves the issue for you? If so we can add a min version constraint to the `tenacity` dependency.

**Comment by AyatoKamina** [comment]
Yeah, I believe it did. I was able to write an output to GCP it seems. Will do some more testing with it.
