### ISSUE TITLE
Recent azure-storage-blob release incompatible with papermill

### ISSUE THREAD

**Issue by MSeal** [nteract/papermill#450]
Something in the import pattern changed and we need to update to be backwards/forwards compatible before the next release.

Changing to azure-storage-blob ~= 2.1 makes tests pass again.

**Comment by cccs-cat001** [comment]
I've noticed this issue as well, if no one else is going to tackle it, I'm giving it a shot to fix.

**Comment by MSeal** [comment]
Please do if you have the time! :)

**Comment by cccs-cat001** [comment]
I've set up a Pull request [here](https://github.com/nteract/papermill/pull/452)

**Comment by MSeal** [comment]
Resolved
