### ISSUE TITLE
Available to NOT save resulting notebook

### ISSUE THREAD

**Issue by vikmary** [nteract/papermill#457]
Hi
My case is that I'm using papermill in unittests. I use it to check whether notebook executes without errors:
```python
class TestNotebook(unittest.TestCase):
    def test_default(self):
        pm.execute_notebook(
           'notebooks/entity_resolution_api.ipynb',
           '/dev/null',
            parameters={}
        )
```

But setting `output_path` with `'/dev/null'` raises a warning. It would be nice to have possibility to not save executed notebook.
Thank you

**Comment by MSeal** [comment]
We get around this in papermill's unittests by doing:

```
    def setUp(self):
        self.test_dir = tempfile.mkdtemp()

    def tearDown(self):
        shutil.rmtree(self.test_dir)
```
This is a little better than passing the /dev/null (no warning) and give the ability to confirm the test outputs during testing more accurately.

In general we don't want to add the option to have no output notebook as it can lead to a pattern of use that's not recommended for users that are new to the application.

**Comment by vikmary** [comment]
Thanks @MSeal 
The workaround you suggested looks good, it should totally remove the unnecessary warnings.
