### ISSUE TITLE
pm.record function

### ISSUE THREAD

**Issue by florathecat** [nteract/papermill#467]
Hi,
I just updated my papermill package to 1.2.1 and found out that the record function no longer works. It just gave me an error message "AttributeError: module 'papermill' has no attribute 'record'".

Is there a replacement function for record? I need it to run multiple jupyter notebooks and import values from each notebook for final combination.

Thanks,

**Comment by MSeal** [comment]
Yes: https://nteract-scrapbook.readthedocs.io/en/latest/ was pulled out about a year ago

**Comment by MSeal** [comment]
Closing this, feel free to comment further if there's follow-up questions.
