### ISSUE TITLE
Close notebook after execution

### ISSUE THREAD

**Issue by Nikolai-Hlubek** [nteract/papermill#479]
When I run `papermill.execute_notebook()` the executed notebook stays in memory and occupies space until I close the parent notebook. 

Is there a way to close the notebook after the execution, while the parent notebook is still running?

**Comment by MSeal** [comment]
Are you referring to the subprocess continuing to alive after execution is completed? I believe https://github.com/jupyter/nbclient/pull/34 fixes the upstream issue with the child process staying open after execution. That should be resolved with the 0.2 release of that package once that merges.

Reverting to papermill 1 should also resolve the issue until papermill 2.0's new dependency fixes the problem.

**Comment by Nikolai-Hlubek** [comment]
Yes I think I'm experiencing this issue. 
I didn't dig deep enough to see that you already fixed this. Thanks a lot. 

I'll check if it works once the new release comes out.

**Comment by MSeal** [comment]
@Nikolai-Hlubek it took a bit longer, but try install papermill 2.1 (or nbclient 0.2) and the issue should be resolved now.

**Comment by Nikolai-Hlubek** [comment]
Thanks @MSeal. It works like a charm now. 

Pushed 332 jobs through the pipeline and had no issues.

**Comment by MSeal** [comment]
Awesome! Glad it resolved the issue.
