### ISSUE TITLE
Papermill adding unusual syntax to HTML stored in JSON

### ISSUE THREAD

**Issue by lwasser** [nteract/papermill#482]
Hi Friends.
I've been using papermill for a while to execute jupyter notebooks in a CI framework. Thank you for your work on it as it's been a fantastic tool.

I'm running into an odd (i think?) bug. When i run a notebook with an interactive element that will require an iframe - case in point creating a map using leaflet (folium for python), it seems to be adding some code that makes the output render incorrectly.

I just ran one of my notebooks. Prior to running papermill, the iframe embed looked like this:
The important piece here is that the `src=data:text/html` part is correctly populated in the json.

```
"<div style=\"width:100%;\"><div style=\"position:relative;width:100%;height:0;padding-bottom:60%;\"><iframe src=\"data:text/html;charset=utf-8;base64,

```
When i run papermill and create a new notebook - for some reason i get the following below: notice that the src now begins with about:blank.

```
"<div style=\"width:100%;\"><div style=\"position:relative;width:100%;height:0;padding-bottom:60%;\"><iframe src=\"about:blank\" style=\"position:absolute;width:100%;height:100%;left:0;top:0;border:none !important;\" data-html=PCFET0NUWVBFIGh0bWw+C
```

can anyone shed some light on why this is happening? it's happening with all of the notebooks that i run through papermill that use folium and have an iframe embed. I just udpated to version 2.0 from 1.2 just as a sanity check and it's still doing the same thing. 

Here is an example of a rendered page where you can see the folium map iframes don't render properly. But i have traced this error back to running papermill as the JSON looks fine prior to running it. Any suggestions for fixing this are much appreciated!

https://www.earthdatascience.org/courses/scientists-guide-to-plotting-data-in-python/plot-spatial-data/customize-raster-plots/interactive-maps/ 

oh i am running papermill on a MAC  with python as follows (i am adding this just in case i'm missing a parameter here):
`pm.execute_notebook(notebook, out_notebook)`

but our CI build is linux and the behavior is the same there. 
many thanks

**Comment by MSeal** [comment]
Thanks for the kind words, we're glad you find the tool helpful. I'm not super familiar with Folium specifically, but it's likely that the library needs to be aware of headless execution modes to output the right IFrame JSON. It may be relying on your browser to build the IFrame payload, which papermill and other backend systems don't have. I'd open an issue in that project, feel free to ping me on it, and I can give guidance or suggestions if the maintainers of that tool have questions.

**Comment by lwasser** [comment]
@MSeal  thank you for the speedy reply! i pinged you in an issue [here](https://github.com/python-visualization/folium/issues/1277) :)

**Comment by MSeal** [comment]
Going to close this issue as I believe it's resolved. Reopen if there's some remaining issues.

**Comment by lwasser** [comment]
thank you @MSeal  it is resolved! i really appreciate your help with it!!
