### ISSUE TITLE
the output is the same as input

### ISSUE THREAD

**Issue by ZahraEconomist** [nteract/papermill#492]
I'm running a simple test , to print a parameter, but I get this error:
``--------------------------------------------------------------------------`
KeyError                                  Traceback (most recent call last)
/usr/local/lib/python3.6/site-packages/traitlets/traitlets.py in get(self, obj, cls)
    527         try:
--> 528             value = obj._trait_values[self.name]
    529         except KeyError:

KeyError: 'kernel_manager_class'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-7-8f156b232705> in <module>
      1 import papermill as pm
----> 2 pm.execute_notebook('/home/zwj750/test.ipynb', '/home/zwj750/test_output.ipynb', parameters=dict(a = 10))

~/.local/lib/python3.6/site-packages/papermill/execute.py in execute_notebook(input_path, output_path, parameters, engine_name, request_save_on_cell_execute, prepare_only, kernel_name, progress_bar, log_output, stdout_file, stderr_file, start_timeout, report_mode, cwd, **engine_kwargs)
    102                     stdout_file=stdout_file,
    103                     stderr_file=stderr_file,
--> 104                     **engine_kwargs
    105                 )
    106 

~/.local/lib/python3.6/site-packages/papermill/engines.py in execute_notebook_with_engine(self, engine_name, nb, kernel_name, **kwargs)
     47     def execute_notebook_with_engine(self, engine_name, nb, kernel_name, **kwargs):
     48         """Fetch a named engine and execute the nb object against it."""
---> 49         return self.get_engine(engine_name).execute_notebook(nb, kernel_name, **kwargs)
     50 
     51 

~/.local/lib/python3.6/site-packages/papermill/engines.py in execute_notebook(cls, nb, kernel_name, output_path, progress_bar, log_output, autosave_cell_every, **kwargs)
    341         nb_man.notebook_start()
    342         try:
--> 343             cls.execute_managed_notebook(nb_man, kernel_name, log_output=log_output, **kwargs)
    344         finally:
    345             nb_man.cleanup_pbar()

~/.local/lib/python3.6/site-packages/papermill/engines.py in execute_managed_notebook(cls, nb_man, kernel_name, log_output, stdout_file, stderr_file, start_timeout, execution_timeout, **kwargs)
    400             stderr_file=stderr_file,
    401         )
--> 402         return PapermillNotebookClient(nb_man, **final_kwargs).execute()
    403 
    404 

~/.local/lib/python3.6/site-packages/papermill/clientwrap.py in execute(self, **kwargs)
     34         self.reset_execution_trackers()
     35 
---> 36         with self.setup_kernel(**kwargs):
     37             self.log.info("Executing notebook with kernel: %s" % self.kernel_name)
     38             self.papermill_execute_cells()

/usr/local/lib/python3.6/contextlib.py in __enter__(self)
     79     def __enter__(self):
     80         try:
---> 81             return next(self.gen)
     82         except StopIteration:
     83             raise RuntimeError("generator didn't yield") from None

~/.local/lib/python3.6/site-packages/nbclient/client.py in setup_kernel(self, **kwargs)
    399         # Can't use run_until_complete on an asynccontextmanager function :(
    400         if self.km is None:
--> 401             self.start_kernel_manager()
    402 
    403         if not self.km.has_kernel:

~/.local/lib/python3.6/site-packages/nbclient/client.py in start_kernel_manager(self)
    326             self.km = self.kernel_manager_class(config=self.config)
    327         else:
--> 328             self.km = self.kernel_manager_class(kernel_name=self.kernel_name, config=self.config)
    329         self.km.client_class = 'jupyter_client.asynchronous.AsyncKernelClient'
    330         return self.km

/usr/local/lib/python3.6/site-packages/traitlets/traitlets.py in __get__(self, obj, cls)
    554             return self
    555         else:
--> 556             return self.get(obj, cls)
    557 
    558     def set(self, obj, value):

/usr/local/lib/python3.6/site-packages/traitlets/traitlets.py in get(self, obj, cls)
    533                 raise TraitError("No default value found for %s trait of %r"
    534                                  % (self.name, obj))
--> 535             value = self._validate(obj, dynamic_default())
    536             obj._trait_values[self.name] = value
    537             return value

~/.local/lib/python3.6/site-packages/nbclient/client.py in _kernel_manager_class_default(self)
    238     def _kernel_manager_class_default(self):
    239         """Use a dynamic default to avoid importing jupyter_client at startup"""
--> 240         from jupyter_client import AsyncKernelManager
    241 
    242         return AsyncKernelManager

ImportError: cannot import name 'AsyncKernelManager'`

**Comment by MSeal** [comment]
You have an old version of jupyter_client -- upgrade that package and it should have the expected class available.
