### ISSUE TITLE
Papermill skip cells execution

### ISSUE THREAD

**Issue by gogasca** [nteract/papermill#494]
Does papermill supports skipping cells ?
I would like to have a cell that contains in metadata a tag called "no_execute" to skip execution. 
More than happy to submit a PR
```
"tags": ["no_execute"]
```
The use case is for example in Cloud we want to skip recreating a Google Cloud Bucket, or authenticate (If we already are).

Currently I use:

```
from nbconvert.preprocessors import Preprocessor
class RemoveCellsWithNoTags(Preprocessor):
    def preprocess(self, notebook, resources):
     executable_cells = []
     for cell in notebook.cells:
            if cell.metadata.get('tags'):
                if 'no_execute' in cell.metadata.get('tags'):
                    continue
            executable_cells.append(cell)
     notebook.cells = executable_cells
        return notebook, resources
```
and nbconvert
```
jupyter nbconvert --Exporter.preprocessors=[\"preprocess.RemoveCellsWithNoTags\"] --ClearOutputPreprocessor.enabled=True --to notebook --output=$NOTEBOOK_NAME_PREPROCESSED $NOTEBOOK_ORIGINAL
```

**Comment by MSeal** [comment]
So it's somewhat of an unresolved issue: https://github.com/nteract/papermill/issues/429

On one hand there's value to aiding in cell skipping, on the other it does add operational complexity to the tool which makes it more difficult to reason about in systems. One of the big benefits of papermill has been the simplicity of the offering and not doing many things.

See what you think on that thread, we haven't closed the door on the idea but I've also been letting it sit for a while before a hard decision is made.

**Comment by gogasca** [comment]
Sounds good, Thanks Matt, will follow up on that thread.
