### ISSUE TITLE
No error message on magic command error

### ISSUE THREAD

**Issue by totycro** [nteract/papermill#501]
Hi,

When I execute a notebook with papermill and a magic command fails, I don't actually get an error message and also the exit code is 0, even though the notebook execution stopped at this point and `metadata.papermill.exception` is set to `true` in the notebook.

I would expect to see a python exception and a non-zero exit code in this case as the execution actually failed.

I've attached a sample input 
[simple.ipynb.txt](https://github.com/nteract/papermill/files/4610414/simple.ipynb.txt) and output [simple_out.ipynb.txt](https://github.com/nteract/papermill/files/4610413/simple_out.ipynb.txt). This is the output i get with debug logging turned on:
```
$ papermill --log-level DEBUG simple.ipynb simple_out.ipynb
Input Notebook:  simple.ipynb
Input Notebook:  simple.ipynb
Output Notebook: simple_out.ipynb
Executing:   0%|                                                            | 0/2 [00:00<?, ?cell/s]Using selector: EpollSelector
Starting kernel (async): ['/opt/conda/bin/python', '-m', 'ipykernel_launcher', '-f', '/tmp/tmpap6uw67z.json', '--HistoryManager.hist_file=:memory:']
Connecting to: tcp://127.0.0.1:57435
connecting shell channel to tcp://127.0.0.1:49455
Connecting to: tcp://127.0.0.1:49455
connecting iopub channel to tcp://127.0.0.1:33771
Connecting to: tcp://127.0.0.1:33771
connecting stdin channel to tcp://127.0.0.1:44405
Connecting to: tcp://127.0.0.1:44405
connecting heartbeat channel to tcp://127.0.0.1:33255
Using selector: EpollSelector
connecting control channel to tcp://127.0.0.1:57435
Connecting to: tcp://127.0.0.1:57435
Executing notebook with kernel: python3
Executing cell:
%env undefined
msg_type: status
content: {'execution_state': 'busy'}
msg_type: execute_input
content: {'code': '%env undefined', 'execution_count': 1}
msg_type: stream
content: {'name': 'stderr', 'text': 'UsageError: Environment does not have key: undefined\n'}
msg_type: status
content: {'execution_state': 'idle'}
Executing:  50%|██████████████████████████                          | 1/2 [00:00<00:00,  1.29cell/s]
$ echo $?
0
```

I'm using papermill 2.1.0.

**Comment by MSeal** [comment]
Thanks for reporting. It looks like the magic function failure here isn't emitting an actual exception output, just stopping the exception event message, which is different than other kernel errors so the logic doesn't capture it correctly when only one half is emitted. I'll look into making a fix for this behavior.

**Comment by Malmurrani** [comment]
Having the same
![image](https://user-images.githubusercontent.com/70553730/132751265-c5558a7b-3100-44da-9c9a-8e5d57ad7bfa.png)

it was working fantastic and suddenly stopped.

import papermill as pm
pm.execute_notebook('C:/Users/malmu/run1.ipynb', 'C:/Users/malmu/result5.ipynb')

any progress please?
Mazin
