### ISSUE TITLE
Issues while installing papermill on mac Mojave OS

### ISSUE THREAD

**Issue by mycarta** [nteract/papermill#503]
I could not install papermill on mac running Mojave (OS 10.14)

It finally worked after I:
1. took care of  gcc with ([from this SO answer](https://stackoverflow.com/a/59161323/1034648)):

```
sudo rm -rf /Library/Developer/CommandLineTools
xcode-select --install
cd /Library/Developer/CommandLineTools/Packages/
open macOS_SDK_headers_for_macOS_10.14.pkg
```

2. updated `regex` with ([from this other SO answer](https://stackoverflow.com/a/59161323/1034648)):
`sudo python3 -m pip install --upgrade regex`

**Comment by MSeal** [comment]
Glad you got you issue self-resolved :)

**Comment by mycarta** [comment]
> Glad you got you issue self-resolved :)

thanks, I thought sharing would be good
