### ISSUE TITLE
Update testing, linting, tox, check-manifest config files

### ISSUE THREAD

**Issue by willingc** [nteract/papermill#505]
Right now check-manifest is throwing an error. I've noticed that we have some settings in tox and duplicated in other files. It's been a while since we updated this so...it's probably time to do so.

**Comment by MSeal** [comment]
Ok I'll try taking a look this week real quick to fix it. There were some updates to tooling libraries to depend on and several merges that might have affected it,

**Comment by willingc** [comment]
I resolved some last night. I think it is just check manifest that is not passing. Sorry about the pushes to master. Thought it would be a quick fix.

**Comment by MSeal** [comment]
No worries, I do the same for these types of things when it doesn't need a review.

**Comment by MSeal** [comment]
Looks like it's all good for now. Going to close the issue.
