### ISSUE TITLE
AttributeError: module 'papermill' has no attribute 'record'

### ISSUE THREAD

**Issue by ucasiggcas** [nteract/papermill#507]
hi,dear
met the error
could you please help me ?
thx
```
>>> import papermill as pm
>>> pm.record()
Traceback (most recent call last):
  File "<pyshell#33>", line 1, in <module>
    pm.record()
AttributeError: module 'papermill' has no attribute 'record'
```

**Comment by MSeal** [comment]
That feature was pulled out of papermill a long while back. It's now in the [scrapbook](https://nteract-scrapbook.readthedocs.io/en/latest/) project as `sb.glue()`.

**Comment by ucasiggcas** [comment]
thx,will close
