### ISSUE TITLE
Update C# translator to support dotnet-interactive, include .net-fsharp and .net-powershell kernels

### ISSUE THREAD

**Issue by jonsequitur** [nteract/papermill#509]
In the most recent preview of .NET's support for Jupyter ([.NET Interactive](https://github.com/dotnet/interactive)), we changed the name of the executable from `dotnet-try` to `dotnet-interactive`, which now supports three .NET languages: C#, F#, and PowerShell: https://devblogs.microsoft.com/dotnet/net-interactive-is-here-net-notebooks-preview-2/ 

@lobrien added support for `dotnet-try` in #448, which should be updated to the new tool, and translators added for the additional languages.

**Comment by jonsequitur** [comment]
@colombod

**Comment by MSeal** [comment]
Thanks for informing about the change.

> @lobrien added support for dotnet-try in #448, which should be updated to the new tool

What changes do you think papermill needs to make? It doesn't directly call the dotnet-try / kernel spec so I _think_ it'll work as is with the new `dotnet-interactive`.

> and translators added for the additional languages

I think the F# translator is already there: https://github.com/nteract/papermill/pull/451
Powershell translator would be a nice improvement, would someone have cycles to open a PR? I'm happy to help review.

**Comment by jonsequitur** [comment]
I hadn't noticed the F# work. The addition of PowerShell support is effectively the same.

Is there documentation that needs to be updated? The prerequisites listed in #448 are no longer correct. The updated install instructions are here: https://github.com/dotnet/interactive/blob/master/docs/NotebooksLocalExperience.md

**Comment by MSeal** [comment]
@jonsequitur We don't really have any instructions per kernel for how to set them up. I'd be open to adding a section to our readtehdocs which links out how to get specific kernels setup.

I think the only requirement here though for papermill is to ass PowerShell support. I think current maintainers are unlikely to get to implementing this, if someone mentioned on this thread could take a stab at it I can help with review / merges.

**Comment by lobrien** [comment]
I don't know PowerShell well enough to write the type mappings myself, but I'd certainly be willing to help any way I can.
