### ISSUE TITLE
Custom comment in injected cell

### ISSUE THREAD

**Issue by edublancas** [nteract/papermill#520]
Currently, the injected cell adds "Parameters" as a comment in the first line. I'm working on a library that uses papermill and would like to customize this behavior to give more information to notebook readers.

Supporting this requires adding a new parameter to `Translator.codify`. https://github.com/nteract/papermill/blob/0532d499e13e93d8990211be33e9593f1bffbe6c/papermill/translators.py#L111

I can put some time to work on this if the proposed change is accepted.

Thanks!

**Comment by MSeal** [comment]
So long as they're new kwargs for the function call I think that's reasonable to add to papermill. Overall sounds like a nice way to support custom parameter generation without doing a full engine registration.

**Comment by edublancas** [comment]
Merged in #521
