### ISSUE TITLE
AttributeError: 'AsyncKernelManager' object has no attribute 'cleanup_resources'

### ISSUE THREAD

**Issue by ak-7** [nteract/papermill#523]
I'm running into the following error. 

`File "carry_only.py", line 35, in <module>
    schedule.run_pending()
  File "/tmp/jupyterlab-akanksha_bindal/jupyterlab-runtime/lib/python3.6/site-packages/schedule/__init__.py", line 563, in run_pending
    default_scheduler.run_pending()
  File "/tmp/jupyterlab-akanksha_bindal/jupyterlab-runtime/lib/python3.6/site-packages/schedule/__init__.py", line 94, in run_pending
    self._run_job(job)
  File "/tmp/jupyterlab-akanksha_bindal/jupyterlab-runtime/lib/python3.6/site-packages/schedule/__init__.py", line 147, in _run_job
    ret = job.run()
  File "/tmp/jupyterlab-akanksha_bindal/jupyterlab-runtime/lib/python3.6/site-packages/schedule/__init__.py", line 466, in run
    ret = self.job_func()
  File "carry_only.py", line 24, in run_main
    'MUVI carry_out.ipynb'
  File "/tmp/jupyterlab-akanksha_bindal/jupyterlab-runtime/lib/python3.6/site-packages/papermill/execute.py", line 104, in execute_notebook
    **engine_kwargs
  File "/tmp/jupyterlab-akanksha_bindal/jupyterlab-runtime/lib/python3.6/site-packages/papermill/engines.py", line 49, in execute_notebook_with_engine
    return self.get_engine(engine_name).execute_notebook(nb, kernel_name, **kwargs)
  File "/tmp/jupyterlab-akanksha_bindal/jupyterlab-runtime/lib/python3.6/site-packages/papermill/engines.py", line 343, in execute_notebook
    cls.execute_managed_notebook(nb_man, kernel_name, log_output=log_output, **kwargs)
  File "/tmp/jupyterlab-akanksha_bindal/jupyterlab-runtime/lib/python3.6/site-packages/papermill/engines.py", line 402, in execute_managed_notebook
    return PapermillNotebookClient(nb_man, **final_kwargs).execute()
  File "/tmp/jupyterlab-akanksha_bindal/jupyterlab-runtime/lib/python3.6/site-packages/papermill/clientwrap.py", line 41, in execute
    self.set_widgets_metadata()
  File "/tmp/jupyterlab-akanksha_bindal/jupyterlab-runtime/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/tmp/jupyterlab-akanksha_bindal/jupyterlab-runtime/lib/python3.6/site-packages/nbclient/client.py", line 443, in setup_kernel
    self._cleanup_kernel()
  File "/tmp/jupyterlab-akanksha_bindal/jupyterlab-runtime/lib/python3.6/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/tmp/jupyterlab-akanksha_bindal/jupyterlab-runtime/lib/python3.6/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/tmp/jupyterlab-akanksha_bindal/jupyterlab-runtime/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
    return future.result()
  File "/tmp/jupyterlab-akanksha_bindal/jupyterlab-runtime/lib/python3.6/site-packages/nbclient/client.py", line 357, in _async_cleanup_kernel
    await ensure_async(self.km.cleanup_resources())`
AttributeError: 'AsyncKernelManager' object has no attribute 'cleanup_resources'
This is my code
```
import papermill as pm
import schedule
import time
import sys
# from send_email import * // this is to assume you write a python send_mail function

# here e2e.ipynb is my input notebook where i have the parameters tag
# e2e_out.ipynb is the output notebook where intermediate results can be saved and viewed later
# you can also add additionals parameters by adding 
# 'parameters = dict(alpha=0.6, ratio=0.1)'
# after the output notebook line

def run_main():
    pm.execute_notebook(
       'MUVI carry.ipynb',
       'MUVI carry_out.ipynb'
    )
#     send_email()

# this allows you to schedule job every day and take an argument of execution time
# to schedule jobs to run every week, or any other frequency, use 
# https://schedule.readthedocs.io/en/stable/ for examples

schedule.every().day.at(sys.argv[1]).do(run_main)

while True:
    schedule.run_pending()
    time.sleep(1)
```

**Comment by MSeal** [comment]
Check your `jupyter_client` version, you likely have a conflicting version of the dependency that didn't update to latest when `nbclient` updated.

**Comment by ak-7** [comment]
That fixed it. Thank you so much!

**Comment by aroraakshit** [comment]
Still facing 
```
HBox(children=(FloatProgress(value=0.0, description='Executing', max=22.0, style=ProgressStyle(description_wid…

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-e8fb920490f0> in <module>
      2     'XGBoost_Demo.ipynb',
      3     'xgb_7_5.ipynb',
----> 4     parameters=dict(max_depth=7, num_rounds=7)
      5 )

/opt/conda/envs/rapids/lib/python3.6/site-packages/papermill/execute.py in execute_notebook(input_path, output_path, parameters, engine_name, request_save_on_cell_execute, prepare_only, kernel_name, progress_bar, log_output, stdout_file, stderr_file, start_timeout, report_mode, cwd, **engine_kwargs)
    104                     stdout_file=stdout_file,
    105                     stderr_file=stderr_file,
--> 106                     **engine_kwargs
    107                 )
    108 

/opt/conda/envs/rapids/lib/python3.6/site-packages/papermill/engines.py in execute_notebook_with_engine(self, engine_name, nb, kernel_name, **kwargs)
     47     def execute_notebook_with_engine(self, engine_name, nb, kernel_name, **kwargs):
     48         """Fetch a named engine and execute the nb object against it."""
---> 49         return self.get_engine(engine_name).execute_notebook(nb, kernel_name, **kwargs)
     50 
     51 

/opt/conda/envs/rapids/lib/python3.6/site-packages/papermill/engines.py in execute_notebook(cls, nb, kernel_name, output_path, progress_bar, log_output, autosave_cell_every, **kwargs)
    341         nb_man.notebook_start()
    342         try:
--> 343             cls.execute_managed_notebook(nb_man, kernel_name, log_output=log_output, **kwargs)
    344         finally:
    345             nb_man.cleanup_pbar()

/opt/conda/envs/rapids/lib/python3.6/site-packages/papermill/engines.py in execute_managed_notebook(cls, nb_man, kernel_name, log_output, stdout_file, stderr_file, start_timeout, execution_timeout, **kwargs)
    400             stderr_file=stderr_file,
    401         )
--> 402         return PapermillNotebookClient(nb_man, **final_kwargs).execute()
    403 
    404 

/opt/conda/envs/rapids/lib/python3.6/site-packages/papermill/clientwrap.py in execute(self, **kwargs)
     46             info_msg = self.wait_for_reply(self.kc.kernel_info())
     47             self.nb.metadata['language_info'] = info_msg['content']['language_info']
---> 48             self.set_widgets_metadata()
     49 
     50         return self.nb

/opt/conda/envs/rapids/lib/python3.6/contextlib.py in __exit__(self, type, value, traceback)
     86         if type is None:
     87             try:
---> 88                 next(self.gen)
     89             except StopIteration:
     90                 return False

/opt/conda/envs/rapids/lib/python3.6/site-packages/nbclient/client.py in setup_kernel(self, **kwargs)
    441         finally:
    442             if cleanup_kc:
--> 443                 self._cleanup_kernel()
    444 
    445     @asynccontextmanager

/opt/conda/envs/rapids/lib/python3.6/site-packages/nbclient/util.py in wrapped(*args, **kwargs)
     72     """
     73     def wrapped(*args, **kwargs):
---> 74         return just_run(coro(*args, **kwargs))
     75     wrapped.__doc__ = coro.__doc__
     76     return wrapped

/opt/conda/envs/rapids/lib/python3.6/site-packages/nbclient/util.py in just_run(coro)
     51         nest_asyncio.apply()
     52         check_patch_tornado()
---> 53     return loop.run_until_complete(coro)
     54 
     55 

/opt/conda/envs/rapids/lib/python3.6/site-packages/nest_asyncio.py in run_until_complete(self, future)
     93                 raise RuntimeError(
     94                     'Event loop stopped before Future completed.')
---> 95             return f.result()
     96         finally:
     97             events._set_running_loop(old_running_loop)

/opt/conda/envs/rapids/lib/python3.6/asyncio/tasks.py in _step(***failed resolving arguments***)
    178                 # We use the `send` method directly, because coroutines
    179                 # don't have `__iter__` and `__next__` methods.
--> 180                 result = coro.send(None)
    181             else:
    182                 result = coro.throw(exc)

/opt/conda/envs/rapids/lib/python3.6/site-packages/nbclient/client.py in _async_cleanup_kernel(self)
    355         finally:
    356             # Remove any state left over even if we failed to stop the kernel
--> 357             await ensure_async(self.km.cleanup_resources())
    358             if getattr(self, "kc") and self.kc is not None:
    359                 await ensure_async(self.kc.stop_channels())
AttributeError: 'AsyncKernelManager' object has no attribute 'cleanup_resources'
```

for running
```
pm.execute_notebook(
    'XGBoost_Demo.ipynb',
    'xgb_7_5.ipynb',
    parameters=dict(max_depth=7, num_rounds=7)
)
```
here is my pip list:
```
notebooks# pip list | grep jupyter
jupyter-client         6.1.3
jupyter-core           4.6.3
jupyter-server-proxy   1.5.0
jupyterlab             1.2.16
jupyterlab-nvdashboard 0.3.1
jupyterlab-server      1.1.5
```

`nbclient is 0.4.1`

Unsure why this error still persists.

**Comment by MSeal** [comment]
If you install jupyter-client == 6.1.3 you get

> nbclient 0.4.1 requires jupyter_client>=6.1.5, but you'll have jupyter-client 6.1.3 which is incompatible.

Unfortunately the nested dependency isn't being respected correctly. See https://github.com/nteract/papermill/issues/526. I'll get a patch release going that should default the nested dependency for better future proofing.
