### ISSUE TITLE
Conda PyPy Build Issue

### ISSUE THREAD

**Issue by MSeal** [nteract/papermill#529]
If someone has time to take a look, the conda recipe is failing for the latest papermill release:
https://github.com/conda-forge/papermill-feedstock/pull/28#issuecomment-675099455

Looks like pypy doesn't like something in the dependencies:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=198336&view=logs&j=aaada960-d85f-5b88-82e5-99df4d27a2ce&t=1169dac8-f5b1-5012-e49a-d6d84b7b929b

**Comment by willingc** [comment]
Did a quick look and we may be running into the ABI stuff for packages that are not installing: https://conda-forge.org/blog/posts/2020-03-10-pypy/

**Comment by willingc** [comment]
Tried a bunch of things to resolve. Ultimately, skipped pypy.
