### ISSUE TITLE
Is it possible to surface an error on an already executed notebook?

### ISSUE THREAD

**Issue by thvasilo** [nteract/papermill#532]
My use-case is kind of like the opposite request of #263, where a CI pipeline launches an independent instance, and I want to test running a notebook in that particular instance/container. The CI pipeline cannot access errors of the separate instance, so my idea was for the instance to put the output notebook in an S3 location that the CI pipeline can access, then do some kind of dry run of the notebook within the CI pipeline, that succeeds if the output notebook on S3 has no errors, or fails otherwise. 

Seems like before #263 this was possible, but not any more.

Any other ideas on how to surface errors from already executed notebooks?

EDIT: Seems like `raise_for_execution_errors` might do the trick? Is this correct usage

```python
import papermill as pm

if __name__ == "__main__":
    nb = pm.execute_notebook(
        "./test-run-out.ipynb", # This is the output notebook run elsewhere, containing a possible error cell.
        "./test-run-out-dry.ipynb", # This is the secondary output notebook
        prepare_only=True)

    # This should raise the correct exception even though the execution above was set with prepare_only=True
    pm.execute.raise_for_execution_errors(
        nb, './test-run-out-dry.ipynb')
```

**Comment by MSeal** [comment]
You've pretty much worked it out. One thing to note is that you can just load the notebook without needing the execute with a dry run first:

```python
nb = pm.iorw.load_notebook_node(my_remote_notebook_path)
pm.execute.raise_for_execution_errors(nb, '/tmp/some-output-name.ipynb') # In theory we could break up raise_for_execution_errors in the future so the output path isn't needed to just raise an exception
```

**Comment by thvasilo** [comment]
Thanks closing this then!
