### ISSUE TITLE
Is it possible to write output_path to Google Cloud Storage URL directly?

### ISSUE THREAD

**Issue by zyxue** [nteract/papermill#533]
I'm using `papermill.execute_notebook` like

```
papermill.execute_notebook(
        input_path='input',
        output_path='output',
)
```

I wonder if output_path can be a GCS URL or some file-like object returned from `with fs.open(...)` from [gcsfs]( https://gcsfs.readthedocs.io/en/latest/).

I see there is a [stdout_file](https://github.com/nteract/papermill/blob/bb8b78b9d6d78c38ff49d7c7a8e50d9899a99808/papermill/execute.py#L24), what does it do, please?

**Comment by MSeal** [comment]
Yes the output path can be a GCS URL via the `'gs://bucket/test.ipynb'` scheme pattern. You do need some additional dependencies that can be installed via `pip install papermill[gcs]`, and you'll need gcs credentials to be able to reach your files (trying without credentials should give you a message about it).

The stdout_file option sets a filepath for the stdout stream from the papermill process in case you want to capture logs about the execution in a file.
