### ISSUE TITLE
Parametrizing jupyter notebooks with R kernel

### ISSUE THREAD

**Issue by absognety** [nteract/papermill#535]
Just wanted to check here, as I have gone through the documentation - Does papermill latest version (2.1.3) currently support R kernels or Julia kernels?
There is papermillr (https://github.com/nteract/papermillr)  in an experimental stage - But I don't think it is under active development.

**Comment by absognety** [comment]
Never mind, I tested the papermill with a sample R kernel and it is working as expected. 
Closing this issue for now.

**Comment by rgbkrk** [comment]
Interesting to look back at this! The papermillr code is an R-equivalent for what is now [scrapbook](https://github.com/nteract/scrapbook).

Thanks for closing this. Maybe I should unarchive `papermillr` to update the README so people can go to the right spot.

**Comment by rgbkrk** [comment]
Went ahead and updated the README for `papermillr`, thanks!
