### ISSUE TITLE
sys.exit isn't handled gracefully in papermill 2.1.3

### ISSUE THREAD

**Issue by ctb** [nteract/papermill#536]
I'd like to stop the execution of a notebook under certain circumstances, and per 

https://papermill.readthedocs.io/en/latest/changelog.html#features

I think I should be able to execute `sys.exit(0)` or `raise SystemExit`, but that doesn't seem to work for me.

This code:

![Screen Shot 2020-09-19 at 11 14 39 AM](https://user-images.githubusercontent.com/51016/93686185-6ae31b00-fa69-11ea-95a6-7435f4f32839.png)

Yields:

![Screen Shot 2020-09-19 at 11 14 30 AM](https://user-images.githubusercontent.com/51016/93686186-6c144800-fa69-11ea-8422-25d25a5e5748.png)

What am I doing wrong? :) 

```
% pip list | grep -i paper
papermill                                 2.1.3
% pip list | grep -i notebook
notebook                                  6.0.3
```

**Comment by willingc** [comment]
Hi @ctb :smile:

Hmm... We're testing `sys.exit(0)`, `sys.exit(1)`, and `sys.exit()` in the Papermill tests. 

This seems to work if I put in a try block:

```
try:
    sys.exit()
except:
    print('Hello')
finally:
    print('Yo')
```

outputting: Hello Yo

and

```
try:
    SystemExit
except:
    print('Hello')
finally:
    print('Yo')
```
Outputs: Yo

@MSeal When support for `sys.exit(0)` was added, were there any constraints on the use cases that would prevent the above?

**Comment by ctb** [comment]
hi @willingc!! Fancy meeting you here!

Well... what should a bare `sys.exit`/`SystemExit` do? I was assuming it would stop the notebook at that cell, which is what I want to do.

**Comment by MSeal** [comment]
A bare `sys.exit(0)` should be making the papermill process exit cleanly. I'll take a look this week at the PR and issue more in depth but can't look much today.

**Comment by ctb** [comment]
thanks, much appreciated! and while I'm at it ...thanks for papermill :)

**Comment by MSeal** [comment]
So @ctb are you just seeing the error message in the notebook or actually seeing the papermill process fail? When sys.exit occurs the kernel process running the notebook still fails with the SystemExit error, we just treat that exception (which is printed in the notebook) as not an error to papermill. Here

```
01:12:03 mseal ~ (venv:.py3local)  
$ papermill Untitled.ipynb Untitled-out.ipynb 
Input Notebook:  Untitled.ipynb
Output Notebook: Untitled-out.ipynb
Executing:   0%|                                                     | 0/3 [00:00<?, ?cell/s]Executing notebook with kernel: python3
Executing:  67%|██████████████████████████████               | 2/3 [00:00<00:00,  2.21cell/s]
01:13:27 mseal ~ (venv:.py3local)  
$ echo $?
0
```

is expected to generate an output that looks like

![sysexit](https://user-images.githubusercontent.com/1863892/94064757-fed12180-fd9e-11ea-8cc7-281ebe7b3051.png)

**Comment by ctb** [comment]
Yes, that's what I see. So that's intentional output, good to know.

I would be interested in a way to stop execution of the notebook without showing such a message :)

**Comment by MSeal** [comment]
There's not an easy way to do that which I am aware of. I image the best way to achieve this would be to extend the  `execute_notebook` from the `NBClientEngine`, and run something akin to `raise_for_execution_errors` but with extra output removal when you find a SystemExit error. Following https://papermill.readthedocs.io/en/latest/extending-entry-points.html#developing-a-new-engine you can register this separate engine.

I'm a little on the fence for if we'd want this behavior in core papermill. The output is somewhat specific to the kernel running the code and seeing where a sys exit occurred can be a desired behavior as it behaves today.

**Comment by ctb** [comment]
ok, I'm not familiar with this and will have to dig in, but I certainly see the point that this is kernel specific! I think we can close this issue - thanks very much for the engagement!
