### ISSUE TITLE
Failure of shell commands is not propagated in any way

### ISSUE THREAD

**Issue by porridge** [nteract/papermill#539]
Consider a cell which contains a `!` command which fails. Papermill does not convey the exit code of the command, so AFAICT it is not possible to verify whether it succeeded or not:

```json
{
 "cell_type": "code",
 "execution_count": 18,
 "metadata": {
  "execution": {
   "iopub.execute_input": "2020-10-07T12:00:19.652204Z",
   "iopub.status.busy": "2020-10-07T12:00:19.651722Z",
   "iopub.status.idle": "2020-10-07T12:00:20.229381Z",
   "shell.execute_reply": "2020-10-07T12:00:20.229779Z"
  },
  "papermill": {
   "duration": 0.599801,
   "end_time": "2020-10-07T12:00:20.229941",
   "exception": false,
   "start_time": "2020-10-07T12:00:19.630140",
   "status": "completed"
  },
  "tags": []
 },
 "outputs": [],
 "source": [
  "! false"
 ]
}
```

**Comment by MSeal** [comment]
This is more of an ipython issue / conversation, if an exception is raised it will correctly propagate to papermill. Changing the `!` behavior there might be a tall order since a lot of notebooks in the wild rely on the silent failure behavior now unfortunately :/

Other ipython magics do raise an exception, like

```
%%bash
false
```

**Comment by porridge** [comment]
> Other ipython magics do raise an exception, like
> 
> ```
> %%bash
> false
> ```

Oooh, thank you for that, this might be sufficient for my purpose! :heart_eyes:

**Comment by MSeal** [comment]
Np. I do know which magics respect process failures is a little bit of a guesswork. Feel free to open an issue in the ipython project if you run into one in the future that you think should be raising when it's not.
