### ISSUE TITLE
Wrong URL for Binder in docs

### ISSUE THREAD

**Issue by bpesquet** [nteract/papermill#542]
On [this page](https://papermill.readthedocs.io/en/latest/usage-workflow.html), the [current URL](https://mybinder.org/v2/gh/nteract/papermill/master?filepath=binder%2Fprocess_highlight_dates.ipynb) for opening "an interactive example that demonstrates the usage of papermill" through Binder is wrong. It seems the `master` branch has been renamed to `main` and the `process_highlight_dates.ipynb` notebook doesn't exist anymore.

Since I don't know which notebook should be opened, I haven't created a PR to solve this issue.

**Comment by rgbkrk** [comment]
It looks like all the references are fixed for `main` in the current repo but that the docs are not up to date.

**Comment by willingc** [comment]
I've deployed the docs on RTD to main. Going to double check the links since I see at least 1 that needs an update. Thanks for the report @bpesquet :sunny:

**Comment by rgbkrk** [comment]
Since it looks like that page is at least fixed I'll go ahead and close this. Thanks for reporting @bpesquet and thanks for fixing the RTD build @willingc!
