### ISSUE TITLE
Failure when a path is pathlib.Path

### ISSUE THREAD

**Issue by drhagen** [nteract/papermill#543]
The Papermill Python API fails if either of the path arguments supplied to `execute_notebook` is a `pathlib.Path`. This is because [`parameterize_path` assumes that the path is always a `str`](https://github.com/nteract/papermill/blob/d5299b0f2705d7a9175c377aa2a2f812c83239e3/papermill/parameterize.py#L50). In order to support parameterized paths, Papermill probably has to continue work with `str`s internally, but it would be nice if Papermill did not fail when given a `Path`. A rasonable fix would be to convert each `Path` object to a `str` before continuing.

**Comment by willingc** [comment]
Thanks @drhagen and @captainsafia. Sounds reasonable to me.
