### ISSUE TITLE
inspect_notebook's inferred_type_name returns None

### ISSUE THREAD

**Issue by DustinKLo** [nteract/papermill#545]
Papermill version: `2.2.0 from /opt/conda/lib/python3.7/site-packages/papermill/cli.py (3.7.6)`
python version: `3.7.6`

I'm testing the `inspect_notebook` function and have my parameters set up like this:
<img width="442" alt="Screen Shot 2020-10-30 at 4 46 23 PM" src="https://user-images.githubusercontent.com/13371881/97765470-79443e00-1acf-11eb-8a71-acde9189da3b.png">

However when I test it it the types returned are `'None'`
in IPython:
```
In [8]: papermill.inspect_notebook('test_notebook.ipynb')
Out[8]:
{'a': OrderedDict([('name', 'a'),
                   ('inferred_type_name', 'None'),
                   ('default', '100.0'),
                   ('help', 'help -- a')]),
 'b': OrderedDict([('name', 'b'),
                   ('inferred_type_name', 'None'),
                   ('default', '"jfksl"'),
                   ('help', 'help -- b')]),
 'c': OrderedDict([('name', 'c'),
                   ('inferred_type_name', 'None'),
                   ('default', '10.2553'),
                   ('help', 'help -- c')]),
 'd': OrderedDict([('name', 'd'),
                   ('inferred_type_name', 'None'),
                   ('default', '[1,2,3,4,5]'),
                   ('help', 'help -- d')])}
```

and in the CLI:
```
$ papermill --help-notebook test_notebook.ipynb
Usage: papermill [OPTIONS] NOTEBOOK_PATH [OUTPUT_PATH]

Parameters inferred for notebook 'test_notebook.ipynb':
  a: Unknown type (default 100.0)
                                  help -- a
  b: Unknown type (default "jfksl")
                                  help -- b
  c: Unknown type (default 10.2553)
                                  help -- c
  d: Unknown type (default [1,2,3,4,5])
                                  help -- d
```

is there something that I'm missing? the example given in the documentation shows the type for each `parameter`
https://papermill.readthedocs.io/en/latest/usage-inspect.html
```
papermill --help-notebook ./papermill/tests/notebooks/complex_parameters.ipynb

Usage: papermill [OPTIONS] NOTEBOOK_PATH [OUTPUT_PATH]

Parameters inferred for notebook './papermill/tests/notebooks/complex_parameters.ipynb':
msg: Unknown type (default None)
a: float (default 2.25)         Variable a
b: List[str] (default ['Hello','World'])
                                Nice list
c: NoneType (default None)
```

Thanks 👍

**Comment by DustinKLo** [comment]
Found the solution, you need to add `# type: <type>` after the variable, but it looks like the "type" can be anything the user defines
```
# parameters cell
a = 4738 # type: int
b = 47892.43 # type: float
c = 'jkdls' # type: str
d = ['hello', 'world'] # type: List[str] other stuff
```

can this be added to the documentation to make it more clear for others in the future? I had to search through the source code to find this
inspect documentation: https://papermill.readthedocs.io/en/latest/usage-inspect.html
example notebook: https://github.com/nteract/papermill/blob/main/papermill/tests/notebooks/complex_parameters.ipynb

**Comment by captainsafia** [comment]
@DustinKLo Thanks for reporting the issue. The parameter inference in papermill supports type annotations and types in comments. The examples in the docs showcase parsing type annotations but type comments are supported as well.
