### ISSUE TITLE
The boto3 optional dependency is missing

### ISSUE THREAD

**Issue by halilduygulu** [nteract/papermill#549]
Hi, we are using `papermill==1.2.1` and it was running fine until this Saturday, 7th of November.
Can you point out what could change in dependent libraries to start giving this exception, it was running and we did not change any code, should be some lib updated.

`papermill.exceptions.PapermillOptionalDependencyException: The boto3 optional dependency is missing. Please run pip install papermill[s3] to install this dependency`

And I could not run with dependency for 1.2.1 version to solve this error. 
```
pip3 install papermill[s3]==1.2.1
zsh: no matches found: papermill[s3]==1.2.1
```

**Comment by halilduygulu** [comment]
it was boto 3 lib update breaking things, reverted to 1.15.x versions.

**Comment by rgbkrk** [comment]
Thanks for closing the issue after figuring this out.
