### ISSUE TITLE
Papermill reorders parameterized table data

### ISSUE THREAD

**Issue by VasuBhog** [nteract/papermill#551]
papermill version: 2.2.2
kqlmagic: 0.1.113.post1
Azure Data Studio: 1.25.0-insider
OS: Darwin x64 19.6.0        

I am currently utilizing papermill with KQL Magic and found that native notebook execution (via jupyter notebook or Azure Data Studio) gives proper table ordering as how it is in the cluster. 
Once I execute papermill via either command line or python API (papermill kusto.ipynb kusto-output.ipynb for example). The outputted parameterized notebook reorders the data within the table but does not change the column headings as shown below. This ends up being a rather serious issue since parameterized notebooks at large would then have faulty data rendering. 

![image](https://user-images.githubusercontent.com/23587151/99110178-9983fa80-25af-11eb-84df-58c44f6b5362.png)

**Left**: Azure Data Studio execution of notebook
**Right**: Papermill parameterized output of the notebook

**Comment by rgbkrk** [comment]
Can you post the raw JSON outputs for these notebooks?

**Comment by VasuBhog** [comment]
Hi @rgbkrk. I posted the gist of the notebooks [here](https://gist.github.com/VasuBhog/7fc3bd1ddf88cc24807498d4c3336cd7). As you can see the ordering of the data is transformed.

**Comment by rgbkrk** [comment]
Looking at cell 3, the only differences in the output data are in output 2:

![image](https://user-images.githubusercontent.com/836375/99133198-cf37dc00-25cd-11eb-801a-f62bb27089fd.png)

In output 3 of cell 3, the data resource json is exactly the same. Is this `Kqlmagic` extension doing anything with the notebook state in javascript?

Here's the notebook I used to look at both of your notebooks (note: I changed the extensions to ipynb): https://gist.github.com/rgbkrk/5375e2da4552c36e805065b4cfe1afce

**Comment by rgbkrk** [comment]
They look good in the notebook too. The only discernable difference here is in the cells that clearly use the extension to force some interactive output in the notebook itself (that won't work headless, as papermill doesn't have a JS context when its running).

![image](https://user-images.githubusercontent.com/836375/99133390-a106cc00-25ce-11eb-9775-d000bda8e9d6.png)

**Comment by VasuBhog** [comment]
@rgbkrk thanks it seems that it was the notebook viewer that must be doing incorrect table rendering upon the papermill parameterized notebook. I had issues viewing the outputted notebook in Jupyter Notebooks viewer, but it seems that may not be the case now.

**Comment by VasuBhog** [comment]
@rgbkrk one question I have is why does papermill reorder table data? Shown below is one of the main differences between the notebooks (linked below)
[input notebook data format](https://gist.github.com/VasuBhog/7fc3bd1ddf88cc24807498d4c3336cd7#file-kql-bug-json-L176)
[papermill output notebook data format](https://gist.github.com/VasuBhog/7fc3bd1ddf88cc24807498d4c3336cd7#file-kql-papermill-json-L168)
and is the reason why this issue is happening in Azure Data Studio.

**Comment by MSeal** [comment]
Papermill doesn't reorder data in any way, and it doesn't manipulate outputs. It's possible to change output ordering by registering a custom extension, but that'd be odd. Is the output data in your input from a vanilla run? It could be your saved input had manipulation by some JS context? Papermill just captures whatever the kernel outputs directly with no manipulation.

**Comment by VasuBhog** [comment]
@MSeal the input notebook utilized KqlMagic and that would be the only factor in this situation. It was a complete vanilla input run, that worked properly and displayed the data format in the same format as the [schema](https://gist.github.com/VasuBhog/7fc3bd1ddf88cc24807498d4c3336cd7#file-kql-bug-json-L78) listed. 

You can see that papermill executed notebook alphabetized the data and pushed the schema toward the end of the application/vnd.dataresource+json (which has reordering in the way the json is setup). I have tested this multiple times (no parameters used) just a clean notebook execution of papermill with kqlmagic, each time papermill seems to reorder the data json as shown in the file.

**Comment by rgbkrk** [comment]
Are you talking about key ordering within the JSON?

**Comment by captainsafia** [comment]
From what I know about the KqlMagic, it renders a table onto the view using an ipywidget (in non-headless mode) so I wouldn't be surprised if there was some default sorting that was applied by the widget that doesn't occur in headless mode.

I also believe that the KqlMagic has some conditional logic in its backend that triggers different logic depending on what front-end it detects is being used so that might have an affect here as well.

**Comment by VasuBhog** [comment]
@rgbkrk 
![image](https://user-images.githubusercontent.com/23587151/99829671-34398780-2b22-11eb-9df4-030c4710166a.png)

![image](https://user-images.githubusercontent.com/23587151/99833029-1a4e7380-2b27-11eb-9c47-d788ec727a0f.png)

The key is alphabetized here within the `application/vnd.dataresource+json` data after the papermill execution. I do not think this is KqlMagic issue as the input notebook was not edited in any way and it orders the data based on the schema. Why would KqlMagic not treat it the same way as the input notebook, only factor would be papermill.
