### ISSUE TITLE
Output always the same as input

### ISSUE THREAD

**Issue by borgdrone7** [nteract/papermill#554]
Hi,

How can I get output to be the same as the one I get when I execute a notebook in Jupyter web app. For example I have one long running cell in which I use %time to measure performance, sometimes output some helpful data, etc. If I run the notebook with execute_notebook I always get as an output file exactly the same file as input without any outputs which would normally happen when using the Jupyter web app.

**Comment by willingc** [comment]
I'm going to close this issue. @borgdrone7 if you have additional questions about papermill's usage, please feel free to ask them here. We can reopen if needed.
