### ISSUE TITLE
New feature: delayed / staggered start of pm.execute_notebook()

### ISSUE THREAD

**Issue by mirekphd** [nteract/papermill#555]
To avoid aggregating multiple memory intensive processing steps at the same moment in time, it would be very useful to be able to start multiple `papermill` runs after a pre-specified random or fixed time delay (e.g. to start 4 jobs at random times within the next 20 minutes, or after 0, 5, 10, 15 minutes delay, to distribute them over time equally). 

It would be sufficient to stagger the start of each pipeline by several minutes, so that the user could schedule multiple jobs without starting them at different times manually (which requires monitoring start intervals).

This is similar to the way that Jenkins job scheduler currently works - by distributing multiple jobs / pipelines over time, so that a minimum possible number of these jobs runs at the same time.

**Comment by MSeal** [comment]
Usually this is achieved by having papermill be call be a cron scheduler, like Jenkins, on a schedule. Papermill doesn't really have an opinion about when or who is launching it, as it's just concerned about each particular execution. I'd suggest looking into schedulers options to approach managing when you execute your code, independent of if the command is `papermill`, `python`, or some other command.

**Comment by willingc** [comment]
Closing this issue as it is resolved. Please use other tools to kick off a schedule. Thanks to all!
