### ISSUE TITLE
Support empty YAML configuration

### ISSUE THREAD

**Issue by dhorgan** [nteract/papermill#558]
Just a suggestion, but it would be nice if empty YAML inputs were allowed. If I run `papermill ... --parameters_file /path/to/empty/file`, it crashes out with the following error:

```python
Traceback (most recent call last):
  File "/usr/local/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/papermill/cli.py", line 228, in papermill
    parameters_final.update(read_yaml_file(files))
TypeError: 'NoneType' object is not iterable
```

The reason for this is that papermill [uses the result of `yaml.load` to update the `parameters_final` dictionary](https://github.com/nteract/papermill/blob/main/papermill/cli.py#L227). When the input to `yaml.load` is empty (either the file is empty or just has some boilerplate comments but no named parameters), then `yaml.load` returns `None`, i.e.

```python
import yaml

# These both evaluate to None
yaml.load('', Loader=yaml.SafeLoader)
yaml.load('# There are no configurable parameters for this notebook', Loader=yaml.SafeLoader)
```

This is a minor gripe and I can work around it, but it would make my orchestration code a lot easier to read if I could just do this and not have to worry about empty files:

```bash
for action in train evaluate do_something_else; do
    papermill "input/${action}.ipynb" "output/${action}.ipynb" --parameters_file "config/${action}.yml"
done
```

The fix here seems easy enough - just change any call to `yaml.load(...)` to `yaml.load(...) or {}`, i.e.

```python
...
parameters_final.update(yaml.load(base64.b64decode(params), Loader=NoDatesSafeLoader) or {})
...
parameters_final.update(read_yaml_file(files) or {})
...
parameters_final.update(yaml.load(params, Loader=NoDatesSafeLoader) or {})
...
```

**Comment by MSeal** [comment]
I'd be fine with this change being made. Happy to merge if someone wants to work on it (I won't directly be able to get to it for a while)

**Comment by ashutoshvarma** [comment]
It would be great if empty YAML doesn't throw an exception (return non-zero).
@dhorgan would you mind if I open a PR with changes you suggest.

**Comment by dhorgan** [comment]
No, not at all! 😄
