### ISSUE TITLE
use modules/functions defined in one notebook in my main notebook.

### ISSUE THREAD

**Issue by motilalmeher** [nteract/papermill#566]
<img width="960" alt="hello" src="https://user-images.githubusercontent.com/49094780/104323129-cef38880-550b-11eb-95b5-417c479ee810.png">
<img width="960" alt="main" src="https://user-images.githubusercontent.com/49094780/104323159-d9ae1d80-550b-11eb-81ad-09f18185a0bf.png">

I need to use modules defined in one notebook in my main notebook. In local I have used %run to run the specific notebook and then I had used the function/modules defined their. Now as %run not working I have used papermill.execute_notebook(,) command to run other notebooks at desired shell. But can not able to use the modules defined in those notebook. Can you please suggest me how to approach this problem.

**Comment by MSeal** [comment]
Papermill (and most notebook executors) use a subprocess to isolate executions to different "kernels" (the process that runs a notebook). Cross-kernel communication is tricky and most systems in Jupyter avoid it as it brings more problems than it solves. Essentially notebooks make poor modules but great integrations. Linking code between notebooks is best in libraries that one notebook calls over cross notebook imports imho.

There are some ways to approach sharing code between notebooks in [nbdev](https://nbdev.fast.ai/) -> [export](https://nbdev.fast.ai/export.html) which basically makes a library module out of a notebook's functions on your behalf. Hopefully that helps cover what you're aiming to achieve.

**Comment by motilalmeher** [comment]
Thank You for your quick response. I will check this approach and let you know.

**Comment by motilalmeher** [comment]
can we use combination of nbdev and papermill in google cloud?

**Comment by MSeal** [comment]
I think you would use one or the other depending on what you're doing. Papermill support GFS sources / destinations to fetch notebooks files if you install with the `papermill[gcs]` extended dependencies. NBdev doesn't reached across system boundaries, so I don't believe it care where you execute. I don't believe it pulls notebooks locally on your behalf though.

**Comment by willingc** [comment]
Closing this issue since it appears to be resolved. Thanks to all!
