### ISSUE TITLE
No parameter translator functions specified for kernel 'pysparkkernel' or language ''

### ISSUE THREAD

**Issue by yedugurinithish** [nteract/papermill#567]
While I try running a notebook (that uses pyspark kernel) using papermill, I get error message "No parameter translator functions specified for kernel 'pysparkkernel' or language ''.

May I know if there is a way to resolve this issue.

**Comment by yedugurinithish** [comment]
Is installing spark on Python kernel the only option to enable papermill on pyspark notebooks.

**Comment by MSeal** [comment]
No, usually kernels registers with the actually underlying language (in this case `python`) as well as their name `pyspark`. Likely this is an issue in the kernel not supplying the appropriate metadata. You can fix this by registering a new pyspark [translator](https://papermill.readthedocs.io/en/latest/reference/papermill-translators.html?highlight=translator):

```python
papermill_translators.register("pyspark", PythonTranslator) # Reuse python translator
```

If the kernel registers as a different language name, change the `pyspark` part to match the kernel language name.

**Comment by MSeal** [comment]
I believe this is not fixed in main -- release going out today
