### ISSUE TITLE
Notebook with exception not persisted in output when run in docker container

### ISSUE THREAD

**Issue by benjamincerigo** [nteract/papermill#580]
Hey,

Currently, we are using `papermill` inside of a docker image and we are having problems with notebooks that have exceptions. The exceptions is not in the output notebook when `papermill` is run in a docker container.

I have made a repo to speed up the debugging process and to show the problem:
https://github.com/datavaluepeople/papermill-docker-error

The readme explains how to run `papermill` in a venv and a docker container and what the results that I am getting.

Does anyone else have any problems with this or know of any solutions?

**Comment by MSeal** [comment]
@benjamincerigo I think you forgot to mount the directory to get the file back out of your docker container.

Add `-v ~/papermill-docker-error:/src` to your docker run command (assuming the repo is checked out in home ~) and you'll get the output notebook as expected with it's exception output saved.

Also ty for the highly detailed notes on the question -- made it really easy to find the problem.

**Comment by benjamincerigo** [comment]
@MSeal Thanks a bunch for the reply. 

Unfortunately, I think your answer is not correct:

For instance, if you run:
```
docker build -t papermill-testing .
docker run papermill-testing cat error_testing.ipynb
```
You can see that the notebook is printed out. 

Explanation of how the notebook gets into the container:
1. When you run `docker build -t papermill-testing .` you build an image with the tag `papermill-testing` using the current `pwd` as the build directory.
2. During the build the `COPY` command in the file `Dockerfile` copies all the code at `.` (build directory) into `.` (WORKDIR). [here](https://github.com/datavaluepeople/papermill-docker-error/blob/3ec390fe1e8e09c55ad4416ce0c6fd0ca1344038/Dockerfile#L9)
3. `docker run papermill-testing papermill error_testing.ipynb error_testing-docker.ipynb` will then use the image that you just build and run the command `papermill error_testing.ipynb error_testing-docker.ipynb` inside.

**Comment by MSeal** [comment]
Right, but you're editing a copy within the container as an output. So the output file update isn't leaving the container unless you mount the filesystem to share it or copy it out explicitly. The COPY command is a 1-time sync into the container rather than a 2-way sync association. Hopefully I'm not missing some part of your question.

**Comment by benjamincerigo** [comment]
Thanks yeah got you: `docker run -v ${PWD}:/src papermill-testing papermill error_testing.ipynb error_testing-docker.ipynb`
