### ISSUE TITLE
How do we reuse engines across executions

### ISSUE THREAD

**Issue by ddreyfus** [nteract/papermill#583]
Apologies if this is a duplicate.
I need to execute multiple notebooks in which each notebook is lightweight.
Think of this as a problem of drawing M notebooks from an N-notebook library, and executing the M notebooks.
I am running into two problems:
1. engine startup time is very high relative to notebook execution time
2. the libraries within the notebook cache content from databases that could be shared across notebook executions

It appears that each notebook execution creates a separate thread. Is this correct?
It would be great to be able to instantiate an engine and then feed it notebooks for processing to address the two issues raised. Is this possible today? If not, what would be involved in making it so?
Alternatively, it would be great to send papermill a list of notebooks and have each one processed with the same kernel.

**Comment by ddreyfus** [comment]
The following code seems to work. 
I started with a copy of the existing code and made a few changes to retain the custom engine across invocations.
Comments?
`

    class CustomEngine(NBClientEngine):
        client = None
    
        @classmethod
        def renumber_executions(cls, nb):
            for i, cell in enumerate(nb.cells):
                if 'execution_count' in cell:
                    cell['execution_count'] = i + 1
    
        @classmethod
        def execute_managed_notebook(
                cls,
                nb_man,
                kernel_name,
                log_output=False,
                stdout_file=None,
                stderr_file=None,
                start_timeout=60,
                execution_timeout=None,
                **kwargs
        ):
            """
            Performs the actual execution of the parameterized notebook locally.
    
            Args:
                nb (NotebookNode): Executable notebook object.
                kernel_name (str): Name of kernel to execute the notebook against.
                log_output (bool): Flag for whether or not to write notebook output to the
                                   configured logger.
                start_timeout (int): Duration to wait for kernel start-up.
                execution_timeout (int): Duration to wait before failing execution (default: never).
            """
    
            # Exclude parameters that named differently downstream
            safe_kwargs = remove_args(['timeout', 'startup_timeout'], **kwargs)
    
            # Nicely handle preprocessor arguments prioritizing values set by engine
            final_kwargs = merge_kwargs(
                safe_kwargs,
                timeout=execution_timeout if execution_timeout else kwargs.get('timeout'),
                startup_timeout=start_timeout,
                kernel_name=kernel_name,
                log=logger,
                log_output=log_output,
                stdout_file=stdout_file,
                stderr_file=stderr_file,
            )
            if not cls.client:
                cls.client = PapermillNotebookClient(nb_man, **final_kwargs)
            # accept new notebook into (possibly) existing client
            cls.client.nb_man = nb_man
            cls.client.nb = nb_man.nb
            # reuse client connection to existing kernel
            output = cls.client.execute(cleanup_kc=False)
            cls.renumber_executions(nb_man.nb)
    
            return output
    
    
    # register reusable kernel
    papermill_engines.register('nbclient_reusable', CustomEngine)
`

**Comment by MSeal** [comment]
Hi @ddreyfus, sorry I didn't see this thread earlier.

> engine startup time is very high relative to notebook execution time

This depends a lot on the kernel and the code you are executing. Some kernels are really slow to launch, but the minimal overhead with the standard engine is the process launch time.

> the libraries within the notebook cache content from databases that could be shared across notebook executions

If the cache is memory based it'll be cleared each run since each run is a new process with fresh memory. If your cache is disk based it can persist across runs (e.g. https://pypi.org/project/CacheMan/).

> It appears that each notebook execution creates a separate thread. Is this correct?
Separate process, not separate thread. But yes.

> It would be great to be able to instantiate an engine and then feed it notebooks for processing to address the two issues raised. Is this possible today? If not, what would be involved in making it so?

I think you got how to do this with your change below.

> Alternatively, it would be great to send papermill a list of notebooks and have each one processed with the same kernel.

We opted to not build this in, since it can cause really unexpected state transfer problems and most Notebooks launch within a second or two and run for much longer than that, so timing for the 95% case didn't make the tradeoff a problem.

> The following code seems to work.
> I started with a copy of the existing code and made a few changes to retain the custom engine across invocations.
Comments?

This is valid to do, however realize you are sharing process memory for each notebook so all your variables from the previous run will be present. Sometimes this is perfectly acceptable but it's not an expected behavior in most situations so we keep the process memory isolated. Additionally you're engine will leave a kernel running indefinitely until the parent process is killed since nothing here cleans up the `cls.client` object.

**Comment by ddreyfus** [comment]
Hi @MSeal ,
Thank you for the response.
To handle the variables left over from a prior run I inject %reset -f.
In my case, papermill runs inside an AWS Lambda dedicated to running notebooks, so the fact that the kernel stays around forever is a feature. ;-)

The other thing I notice, running in the AWS environment, is that a good chunk of time is spent writing to S3.
Again, perhaps for the 95% case this time is tiny relative to notebook execution time. My solution was to also provide an S3 handler subclass that would queue save requests and have a thread pool write behind.

Notebook publishing is now 5-10X faster. YMMV.

Thank you
