### ISSUE TITLE
How to retrieve the outputs of a Notebook using Papermill?

### ISSUE THREAD

**Issue by lilianabrandao** [nteract/papermill#597]
I would like to use Papermill to build a pipeline of integrated Jupyter Notebooks. For that, I need to pass the outputs of a Notebook to the following one. 

How can I do this? Does Papermill have a function that allows me to retrieve the outputs of a Notebook in order to use them as parameters in another Notebook? 

Any help would be much appreciated.

**Comment by yechiav** [comment]
hey 
i think this might do the trick
https://github.com/nteract/scrapbook

**Comment by MSeal** [comment]
Yep, [scrapbook](https://nteract-scrapbook.readthedocs.io/en/latest/) was extracted from papermill to it's own library a while back and is intended to address sharing outputs from notebooks.

**Comment by lilianabrandao** [comment]
Thank you  @yechiav and @MSeal for the help. Indeed, scrapbook is what I need. 

However, the reglue method does not seem to be working for me...
Notebook 1:
```
(...)
data_structure = scaler.fit_transform(features).tolist()

sb.glue("data_structure", data_structure)
```

Notebook 2:
```
nb = sb.read_notebook(notebook1_path)
print(nb.reglue("data_structure"))
```

But I get "None".

Any clue about what I'm doing wrong?
Thanks

**Comment by MSeal** [comment]
`reglue` saves the contents into your outputs but doesn't echo anything to a variable. What you're looking for is the [scraps api](https://nteract-scrapbook.readthedocs.io/en/latest/usage-read-notebook.html#scraps), specifically `scraps.data_dict` if you want to pull that data attribute into memory:

```
nb = sb.read_notebook(notebook1_path)
print(nb.scraps.data_dict["data_structure"])
```

**Comment by lilianabrandao** [comment]
Thank you @MSeal ! I'm now able to save the output of a Notebook into a variable and use it as a Papermill parameter for the next Notebook in the pipeline.
