### ISSUE TITLE
FutureWarning when importing pyarrow.HadoopFileSystem

### ISSUE THREAD

**Issue by tlinhart** [nteract/papermill#600]
I'm getting this warning when using papermill (as a library from Python script):

```
WARNING:papermill:/home/pasmen/xxx/venv/lib/python3.8/site-packages/papermill/iorw.py:50: FutureWarning: pyarrow.HadoopFileSystem is deprecated as of 2.0.0, please use pyarrow.fs.HadoopFileSystem instead.
  from pyarrow import HadoopFileSystem
```

I'm using Python 3.8 with papermill 2.3.3 and pyarrow 4.0.0 (installed implicitly as a papermill dependency).

The fix should be straightforward, I might try to prepare PR if interested.

**Comment by willingc** [comment]
Thanks @tlinhart for the report.

**Comment by MSeal** [comment]
@tlinhart a PR to fix would be wonderful if you do have time. Always happy to get the future warnings resolved early.

**Comment by abhimanyu-bitsgoa** [comment]
Hi!
I just created a pull request to address this issue. Needed to call a different import as shown [here](https://arrow.apache.org/docs/python/generated/pyarrow.hdfs.connect.html).
Kindly review.
