### ISSUE TITLE
Move black dependency to dev requirements file

### ISSUE THREAD

**Issue by willingc** [nteract/papermill#612]
Black is currently miscategorized in `requirements.txt` and should be a development dependency. Black isn't needed to build the papermill package.

This would be a good issue for someone after PR #611 lands.

**Comment by MSeal** [comment]
It actually is used in code for Python parameter translation: https://github.com/nteract/papermill/blob/d77db79b8620bb3d922f8a4cf0718aa9725bd423/papermill/translators.py#L184-L193

When parameters are large this helps a lot with readability.

**Comment by MSeal** [comment]
I'm going to close the issue for now since it's being used by the program itself. Happy to reopen if changes are requested.

**Comment by willingc** [comment]
Sounds good @MSeal. Do we want to comment the requirements file to say this?

**Comment by MSeal** [comment]
That's probably a good idea, just make sure the requirements parser in setup ignored the comment correctly (it's a naive parser)
