### ISSUE TITLE
Suppress excessive output

### ISSUE THREAD

**Issue by roger-yu-ds** [nteract/papermill#632]
## 🚀 Feature
A parameter to suppress excessive output in Jupyter.

### Motivation
papermill version: 2.3.3
When the `pm.execute_notebook()` is complete in Jupyter, it seems that the output notebook contents is printed (see image below)
![image](https://user-images.githubusercontent.com/7835508/136132979-43812462-6ee6-48ec-a5d5-ce35347d3686.png)

The output which makes the control notebook very long. Furthermore, that printed output is not human friendly.

**Comment by MSeal** [comment]
@roger-yu-ds The execute_notebook function returns the output notebook object. The cell there is rendering the last returned value, as Jupyter does in cell executions. Put a `;` on the end of that execute call, or assign it to a variable (`nb = pm.execute_notebook(...)`) and it'll not print the resulting notebook document.

**Comment by roger-yu-ds** [comment]
Right! I just tested it and it works as expected! Thanks for the tip.
