### ISSUE TITLE
New release after 2.3.3

### ISSUE THREAD

**Issue by dhimmel** [nteract/papermill#642]
Any plans for a new release?

Noting the last release [2.3.3](https://github.com/nteract/papermill/releases/tag/2.3.3) was from 2021-03-09 and there have been 40+ [commits since then](https://github.com/nteract/papermill/compare/2.3.3...3002e9f4c).

Particularly excited for the removal of some warnings like https://github.com/nteract/papermill/issues/600.

**Comment by sreerajkksd** [comment]
@willingc Would you be able to release a new version? You seems to have contributed a lot of changes recently and probably in a better to position to comment/handle this. Thanks.

**Comment by willingc** [comment]
@sreerajkksd @dhimmel Let me chat with @MSeal about cutting a release. Seems like a good time to do so.

**Comment by MSeal** [comment]
2.3.4 is out on PyPI and the conda forge build triggers should follow shortly. I'll keep an eye for any issues with the conda forge auto PRs (sometimes it take a day for those to come through). For now I'm going to close this issue. Thanks @willingc for preparing the release.

**Comment by wholtz** [comment]
The release of 2.3.4 has not been tagged. It would be nice to have that for consistency.
