### ISSUE TITLE
Prepare release 2.3.4

### ISSUE THREAD

**Issue by willingc** [nteract/papermill#644]
To Do
- [x] Add Python 3.10 support to CI, tox, and docs
- [x] Update changelog
- [x] Update README
- [x] Release to PyPI
- [x] Release to conda-forge

**Comment by willingc** [comment]
Related to #642

**Comment by rwmajor2** [comment]
@willingc Just checking in on this status.

**Comment by willingc** [comment]
@rwmajor2 Just waiting for @MSeal to get a chance to review the two open PRs. Between the holidays and illnesses, we are doing our best :sunny: If you wish to test/review the release related PRs, that would be helpful too. Thanks for your patience.

**Comment by MSeal** [comment]
Apologies, as Carol said illness has delayed responsiveness on my end here. I'll look into any open PRs and get a release going today :)
