### ISSUE TITLE
pd.set_option not recognized in Papermill run

### ISSUE THREAD

**Issue by mix-protocol** [nteract/papermill#651]
First of all, I'd like to thank you all for this great project—opens up many possibilities with Jupyter notebook. I've been experimenting with Papermill over the last couple of days and just stumbled upon an issue I can't figure. It's definitely not critical, but slightly annoying.

Basically, I have a Jupyter notebook that displays DataFrames. Within the notebook, I set `pandas` formatting to be:

```
pd.set_option('display.precision', 2)
pd.set_option('display.float_format', '{:.2f}'.format)
pd.set_option('display.html.border', 1)
pd.set_option('display.show_dimensions', False)
```

If I run the notebook interactively on my machine, the DataFrames show as expected (with 2 decimal places). However, after using Papermill to run, the output notebook displays the default (6 decimal places). I've tried to place the `pandas` formatting code before and after parameter injection, and it doesn't seem to change. Any ideas on further investigating the issue?

**Comment by MSeal** [comment]
Try printing the options right before it generates the plots with [get_option](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.get_option.html#pandas.get_option). See if something else is overriding it. Papermill doesn't manipulate pandas settings in anyway so it shouldn't interfere with what you set unless something overrides the values after you set them. Beyond that I'm not sure why those settings wouldn't be preserved.

**Comment by mix-protocol** [comment]
Hey @MSeal, thanks for the comments. Tried that and seemed to be working fine. On closer inspection I noticed a difference in `pandas` versions (`1.3.5` in my Jupyter environment, `1.4.1` in Papermill). Downgrading from `1.4.1` to `1.3.5` helped to solve the issue. Thanks for the help!
