### ISSUE TITLE
use unittest.mock instead of mock

### ISSUE THREAD

**Issue by pgajdos** [nteract/papermill#659]
## 🐛 Bug

Could you please consider unittest.mock instead of mock everywhere consistently or at least use unittest.mock as a fallback when mock is not installed?

**Comment by reoono** [comment]
Thank you for creating the issue.
As I have created the PR, please check it when you have free time.

**Comment by pgajdos** [comment]
@reoono, tested with python 3.8, 3.9 and 3.10, works nicely. Thanks!

**Comment by MSeal** [comment]
Merged, ty for the contribution!
