### ISSUE TITLE
Append instead of replace parameter cell

### ISSUE THREAD

**Issue by MSeal** [nteract/papermill#68]
Cells overwrite the contents of the parameter tagged cell which is non-intuitive and easy to mess up. Instead it would be more reasonable if the tagged cell used values there as default values and simply appended its contents to the cell definition. Repeated names would still be overwritten and non-papermill execution could enumerate sane values without breaking papermill execution as it is today. But, it would allow for easier assignment of defaults without adding a new cell. Today all the notebooks I've seen for papermill leave a blank cell for parameters which has to be explained to each person who sees a papermill notebook as opposed to a normal notebook when there shouldn't be so much of a difference.

**Comment by rgbkrk** [comment]
Yeah, I would definitely love if the values in the cells were treated as default values and left if not overridden.

**Comment by betatim** [comment]
(related #54)
