### ISSUE TITLE
Ansiwrap raises no module found error due to use of deprecated imp command

### ISSUE THREAD

**Issue by soggyomelette** [nteract/papermill#680]
## 🐛 Bug

When bundled using PyInstaller, ansiwrap is unable to find textwrap3 using the imp command leading to a no module found error as shown below.
![image](https://user-images.githubusercontent.com/85685255/189323260-a4dbd229-84b6-4499-bcdb-634a96c94419.png)

Since the repo hasn't been updated in ages (https://github.com/jonathaneunice/ansiwrap) and there is only one instance of its usage in papermill, the best solution should be to remove its usage from the repo.

**Comment by MSeal** [comment]
This could be resolve with the merged PR and in the next release.

**Comment by piiq** [comment]
Hi @MSeal, thanks for reviewing and merging https://github.com/nteract/papermill/pull/681
Is there a timeline for a release that would include this change and is there anything I can do to help making that release?
