### ISSUE TITLE
Respect Notebook nbformat version

### ISSUE THREAD

**Issue by martinRenou** [nteract/papermill#686]
## 🐛 Bug

It looks like papermill uses `nbformat.v4` in multiple places of the code.

It should probably respect the nbformat that the Notebook being processed uses (looking at the `nbformat` and `nbformat_minor` versions from the Notebook)?

**Comment by martinRenou** [comment]
I have a more specific case happening locally:

Papermill is modifying my Notebook `v4.4` ("id" is not a valid cell property for this version).
It adds a new cell to the Notebook with `nbformat.v4.new_code_cell`, which adds an "id" to this cell. I suppose it cannot to better than this, because AFAICT nbformat has no way to do something like `nbformat.v4.4.new_code_cell`.
My Notebook ends up invalid for `v4.4`, so papermill should probably bump my Notebook version to `v4.5`.

**Comment by martinRenou** [comment]
Which means the wishlist for this issue is the following:

- Use `nbformat.v*.new_code_cell` respecting the Notebook's `nbformat` version
- Bump the Notebook's `nbformat_minor` version

**Comment by MSeal** [comment]
@martinRenou I agree and at this point 4.4 is quite old of a format and I don't see any reason to not just upgrade notebooks to 4.5 upon execution if they are older.

**Comment by martinRenou** [comment]
I can make a PR :)
