### ISSUE TITLE
Debug / Skip cell tag

### ISSUE THREAD

**Issue by MSeal** [nteract/papermill#69]
It'd be useful to have an additional tag which tells papermill to skip particular cells. This would enable cells which have lots of prints, long outputs, or graph outputs which aren't needed for all run to be visible in the notebook but not run on each papermill execution.

**Comment by rgbkrk** [comment]
Would that break the perception of a linear flow of a notebook run by papermill?

I guess this kind of leads towards a desire to stitch notebooks together in parts rather than always having the whole document. It's useful to have them together when authoring, when run as a job though you want a limited view I suppose?

**Comment by betatim** [comment]
What about supporting something like `papermill step1.ipynb step2.ipynb outputs/` which then generates `outputs/combined.ipynb`? I'd rather compose notebooks on the command line than have annotations on cells to run/not run them.

**Comment by hoangthienan95** [comment]
Has this feature been implemented? It'd be useful for debugging and/or Demo-ing a portion of the script at the end of the notebook, along with discussing design choices, sample data, analysis etc. When run on real data, the demo will be skipped. Right now I'm commenting the demo out and have to undo everytime I want to debug/show demo. Is it recommended that we keep 2 separate notebooks in this case? Keeping them up to date/coupled with each other can be a nuisance.

**Comment by MSeal** [comment]
No, overall I think it's in the realm of potentially nice but complex. We've been leaning to keeping the repo simple over convenience features. One way you can control this today is to gate your demo cell with an `if demo:` wrapper and then set that in papermill `-p demo on` or at the top of the notebook when you want the demo activated.

I think I'm going to close this issue based on the trade-off discussions we've had in the past on related topics. If notebook format adopts a skip flag then we'll reopen this issue and address matching compatibility with other interfaces.
