### ISSUE TITLE
Example on how to parameterize markdown cells

### ISSUE THREAD

**Issue by avivajpeyi** [nteract/papermill#713]
Could someone point me to an example of how I can parameterize a markdown cell? 

This would be useful to set the title of notebooks (the notebooks are the same, just different title and different parameterized code cell). 

ATM I am reading the notebook, and replacing the title string, but maybe there is a better "papermill" way of doing this?

**Comment by avivajpeyi** [comment]
@edublancas suggested the following: 

> you can create dynamic markdown cells but you'd have to put some code cells at the top and then the markdown cell, so something like this
```
# cell 1: parameters

# cell 2: injected parameters

# cell 3
from IPython.display import Markdown
Markdown(f" # {variable}")
```

It may be nice to include this in an example :)

**Comment by edublancas** [comment]
sure, feel free to open a PR!

perhaps we can create a new file under the How-To section?

**Comment by avivajpeyi** [comment]
I decided to use a find-replace `{{variable}}` as I dislike having an extra code cell to generate the markdown.
