### ISSUE TITLE
Cell that starts with %%time does not report errors

### ISSUE THREAD

**Issue by vincent-163** [nteract/papermill#781]
## 🐛 Bug

Running a new notebook with two cells via papermill: (assuming `results.json` does not exist)

```python
%%time
# cell 1
with open('results.json') as f:
    results = json.load(f)
```

```python
print(results)
```

Gives
```
NameError: name 'results' is not defined`
```
for the second cell. The first cell's error is silently ignored without any warnings, and the only clue is that the cell's time is not reported as well.

If `%%time` is removed from the first cell, the error is reported properly and the execution is interrupted at the first cell:
```
FileNotFoundError: [Errno 2] No such file or directory: 'results.json'
```

**Comment by zmbc** [comment]
This is actually an upstream issue in IPython: https://github.com/ipython/ipython/issues/12971

**Comment by MSeal** [comment]
I put a comment on that thread, it is indeed a magic implementation issue and not a notebook or papermill specific control point.
