### ISSUE TITLE
Begin using pytest to simplify tests

### ISSUE THREAD

**Issue by willingc** [nteract/papermill#82]
Let's start using pytest with future tests since they are simpler to write and maintain. This should result in better code coverage over time.

**Comment by rgbkrk** [comment]
We're using pytest, I'm a little confused.

**Comment by willingc** [comment]
A lot of the tests themselves are using unittest instead of the pytest structure.

**Comment by rgbkrk** [comment]
Ohhhhhh, thanks!

**Comment by willingc** [comment]
My goal is to confuse ;-)

**Comment by willingc** [comment]
Let's move forward in general with pytest for new tests unless there is a particular test that would be better implemented using unittest.

**Comment by betatim** [comment]
I am happy to answer questions about "How to do X with pytest". We wrote a lot of pytest-onic test code for [khmer](//github.com/dib-lab/khmer) and [scikit-optimize](//github.com/scikit-optimize/scikit-optimize) that I can crib from :)
