### ISSUE TITLE
Refactor python2 handling after increasing test coverage

### ISSUE THREAD

**Issue by willingc** [nteract/papermill#96]
There's a bit of inconsistency of how Python2 is being used alongside Python 3. After test coverage is at 80% ish, we should consider refactoring which libraries are used to best support python2 and python3 so that the code base essentially handles both with a minimum of "if 2" or "if 3". Focus on selecting the best practices for migration from 2 to 3.

**Comment by willingc** [comment]
cc / @MSeal @betatim @rgbkrk

**Comment by betatim** [comment]
I think there is already use of `six` so we should build on that and switch things which deviate from that to using `six`.

For example https://github.com/nteract/papermill/blob/3fa2fabce27f64f62bf16e361cff4b94dcd83491/papermill/tests/test_execute.py#L18-L20 should use `six.PY2`.

**Comment by MSeal** [comment]
Yes agreed to all of that. Between six and future we should be able to get the explicit branching factor down a lot.

**Comment by MSeal** [comment]
Gonna close this issue, as more likely we'll be removing python 2 support before we do more of this. Also our test coverage is much higher now with the existing code.
